pachli/pachli-android

CLA_ENTITY.md, CLA_IC.md, README.md, doc/CLAs.md
Ensure contributions are appropriately licensed by requiring new contributors sign a CLA.
CLAs are from https://contributoragreements.org/agreement-chooser.html, and https://cla-assistant.io is configured in the repository to present the CLA to first-time contributors when they propose a PR.
=> docs: Add contributor license agreements

PRIVACY.md, app/lint-baseline.xml, app/src/main/AndroidManifest.xml
While drafting the policy I noticed that the `READ_MEDIA_*` permissions could be added (for newer devices), the `ACCESS_NETWORK_STATE` permission was missing, and `VIBRATE` was unnecessary.
=> docs: Add a privacy policy

app/src/main/java/app/pachli/StatusListActivity.kt, app/src/main/res/values/strings.xml
Previous code created hashtag filters without the `#`, so muting the tag `#something` would filter all posts that contained `something`, with or without the `#`.
Fix this when creating filters, and only remove filters (when unmuting) if the title and contents match.
Show a snackbar when hashtags are successfully muted/unmuted, so the user is aware something happened.
=> fix: Create hashtag filters with the `#` character

.github/workflows/ktlint.yml
The permission declaration appears to be sensitive to the position in the file. Move it to the start to ensure it takes effect.
=> ci: Move reviewdog permissions block

app/src/main/java/app/pachli/util/LinkHelper.kt
The previous code was operating on the wrong text, resulting in normal URL spans (which have an underline) being applied, instead of the correct spans (which don't).
Fix this by using the correct length.
=> fix: Apply setClickableText correctly, prevent spurious underlines

app/lint-baseline.xml, app/src/main/java/app/pachli/StatusListActivity.kt, app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt, app/src/main/java/app/pachli/interfaces/AppBarLayoutHost.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_search.xml, app/src/main/res/layout/activity_view_thread.xml, app/src/main/res/layout/fragment_timeline.xml, app/src/main/res/layout/toolbar_basic.xml
Scrolling a thread, set of search results, or viewing a thread would cause the toolbar to flicker as items moved under it.
Fix this by configuring the toolbar to `liftOnScroll` in the relevant layouts.
It needs to be configured with the view (or ID of the view) that it will be scrolling. For views that are in the same layout this is done with the `liftOnScrollTargetViewId` attribute.
For views that are in different layouts (e.g. the toolbar is in the activity and the scrolling view is in a fragment) the app bar's `setLiftOnScrollTargetView` method must be called.
Do this in `TimelineFragment` if the hosting activity is a new interface `AppBarLayoutHost`. Implement this interface in `StatusListActivity`.
Update the relevant layouts to use `MaterialToolbar`.
Fixes #21
=> fix: Fix toolbar flickering when scrolling lists

app/lint-baseline.xml, app/src/main/java/app/pachli/components/conversation/ConversationsFragment.kt, app/src/main/java/app/pachli/components/followedtags/FollowedTagsActivity.kt, app/src/main/java/app/pachli/components/notifications/NotificationsFragment.kt, app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt
The previous code didn't collect the uiState, so it was fixed at the default value, ignoring any changes that happened over the life of the viewmodel.
Fix that, so that the FAB will hide/show on scroll according to the user's preferences.
While I'm here simplify the show/hide logic. The previous code would ignore the user's preference if scrolling up. There doesn't seem to be a good reason for that, and spelunking 6+ years back through the history didn't find a justification for that behaviour in the original commit.
Fixes #15
=> fix: Show the FAB according to the user's preferences

app/lint-baseline.xml, app/src/main/java/app/pachli/ListsActivity.kt, app/src/main/java/app/pachli/TabPreferenceActivity.kt, app/src/main/java/app/pachli/components/accountlist/AccountListFragment.kt, app/src/main/java/app/pachli/components/announcements/AnnouncementsActivity.kt, app/src/main/java/app/pachli/components/conversation/ConversationsFragment.kt, app/src/main/java/app/pachli/components/drafts/DraftsActivity.kt, app/src/main/java/app/pachli/components/followedtags/FollowedTagsActivity.kt, app/src/main/java/app/pachli/components/instancemute/fragment/InstanceListFragment.kt, app/src/main/java/app/pachli/components/notifications/NotificationsFragment.kt, app/src/main/java/app/pachli/components/report/fragments/ReportStatusesFragment.kt, app/src/main/java/app/pachli/components/scheduled/ScheduledStatusActivity.kt, app/src/main/java/app/pachli/components/search/fragments/SearchAccountsFragment.kt, app/src/main/java/app/pachli/components/search/fragments/SearchHashtagsFragment.kt, app/src/main/java/app/pachli/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt, app/src/main/java/app/pachli/components/viewthread/ViewThreadFragment.kt, app/src/main/java/app/pachli/components/viewthread/edits/ViewEditsFragment.kt
Switching to the Material 3 themes caused the previous list dividers to disappear.
Replace `DividerItemDecoration` with `MaterialDividerItemDecoration` to restore them.
=> change: Restore dividers between list items

app/src/main/res/drawable/ic_launcher_monochrome.xml
The icon was appearing zoomed in when the user enabled theming in the launcher.
Scale and translate the path to position it correctly.
=> fix: Scale the monochrome icon to fit

app/src/main/res/layout/item_tab_preference.xml
The chips for adding a new hashtag to a tab specified the background colour without setting the text colour, resulting in the colour being too low-contrast against the background.
Use `?colorOnPrimary` to get the correct colour.
=> fix: Use the correct contrast colour on hashtag tab chips

app/src/main/java/app/pachli/components/accountlist/AccountListActivity.kt, app/src/main/java/app/pachli/components/accountlist/AccountListFragment.kt, app/src/main/java/app/pachli/components/filters/FiltersActivity.kt, app/src/main/java/app/pachli/components/followedtags/FollowedTagsActivity.kt, app/src/main/java/app/pachli/components/scheduled/ScheduledStatusActivity.kt
Testing showed additional activities with toolbar flicking issues. Fix as before, using `setLiftOnScrollTargetView` to specify the scrolling view the toolbar should lift above.
=> fix: Fix toolbar flickering in additional activities

app/lint-baseline.xml, app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt
The previous code only attempted to restore the user's reading position once, after any initial refresh.
Adjust this so the position is restored after any refresh (which may have been triggered from a menu instead of a swipe), and use `scrollToPositionWithOffset` to ensure it's visible.
=> fix: Restore the user's reading position in more circumstances

.github/workflows/upload-blue-release-google-play.yml
This action should build the APK and AAB, sign them, and store the APK as an asset.
Uploading to the correct Google Play release track will come later.
=> ci: Start creating the build / sign / upload-to-Google-Play pipeline

app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt
Fetching data for a cached timeline can start on `onCreateView`, as soon as the `viewLifecycle` state transitions to `CREATED`.
=> change: Fetch cached timeline when lifecycle is CREATED

app/src/main/res/layout/dialog_mute_account.xml
The previous code used "?attr/colorOnTertiary", which is the wrong colour for the default background. Remove the override, so the correct styled colour is used.
=> fix: Use correct colour on "mute account" dialog

app/src/main/java/app/pachli/settings/SettingsDSL.kt
The previous code used SwitchPreference to generate the switches, which didn't apply the Material colours. This made it difficult to distinguish between the on/off states, as the non-Material colours for those states are very similar.
Fix by using SwitchPreferenceCompat which uses the correct Material colours.
=> fix: Use correct colours for preference switches

.github/workflows/upload-blue-release-google-play.yml
Add additional steps which:
- Generate the whatsnew-en-US file from the Fastlane metadata
- Uploads the generated AAB file to Google Play
=> ci: Support generating whatsnew and uploading to Google Play

.github/workflows/ci.yml, .github/workflows/ktlint.yml, .github/workflows/populate-gradle-build-cache.yml, .github/workflows/upload-blue-release-google-play.yml, docs/contributing/code.md
The separation between the `develop` and `main` branches was inherited from Tusky and isn't helpful, complicating the release process and causing CI to repeatedly run the same actions on the same code.
Deprecate the `develop` branch by removing references to it in the documentation and updating the CI configuration as necessary.
Separately, the GitHub settings will be changed to set `main` as the default branch, and the `develop` branch will be deleted.
=> change: Deprecate the "develop" branch

app/src/main/java/app/pachli/adapter/PollAdapter.kt
Draw poll bars using the container colour variants to ensure that the text drawn on top is also visible against the background.
Fixes #85
=> fix: Ensure poll option text is visible against the background

app/lint-baseline.xml, app/src/main/java/app/pachli/adapter/PollAdapter.kt, app/src/main/java/app/pachli/adapter/StatusBaseViewHolder.java
Previously the voting button was always enabled, even if the user hadn't made a choice.
Disable the button by default, and listen for clicks on the options. Enable the button whenever one or more options are selected.
Fixes #90
=> fix: Enable/disable vote button when the user can/can't vote

app/src/main/java/app/pachli/components/conversation/ConversationsFragment.kt, app/src/main/java/app/pachli/components/report/fragments/ReportStatusesFragment.kt, app/src/main/java/app/pachli/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/app/pachli/components/viewthread/ViewThreadFragment.kt
Previous code created `statusDisplayOptions` in full each time, risking the creation of inconsistent states / defaults.
Refactor to use `StatusDisplayOptions.from()` so the user's settings (and defaults) are always respected.
=> refactor: Ensure `statusDisplayOptions` are created consistently

app/src/main/java/app/pachli/components/viewthread/ViewThreadViewModel.kt
A previous change dropped the check to see if media was marked as sensitive, and so all media was hidden when viewing a thread. Reinstate the check so only sensitive media is hidden (if the user preferences are set that way).
=> fix: Show media when opening a thread, based on user preferences

.github/workflows/ktlint.yml
Previously the permissions were only applied to branches from this repository, not forks. Use `pull_request_target` so the `GITHUB_TOKEN` will have the correct permissions when this workflow is run from a PR created from a clone.
Remove the `issues` permission, it didn't seem necessary.
=> ci: Run ktlint workflow on forks, with write permissions

app/lint-baseline.xml, app/src/main/res/layout-sw640dp/fragment_timeline.xml, app/src/main/res/layout-sw640dp/fragment_timeline_notifications.xml, app/src/main/res/layout/activity_announcements.xml, app/src/main/res/layout/activity_drafts.xml, app/src/main/res/layout/activity_filters.xml, app/src/main/res/layout/activity_followed_tags.xml, app/src/main/res/layout/activity_lists.xml, app/src/main/res/layout/activity_scheduled_status.xml, app/src/main/res/layout/fragment_account_list.xml, app/src/main/res/layout/fragment_accounts_in_list.xml, app/src/main/res/layout/fragment_instance_list.xml, app/src/main/res/layout/fragment_lists_for_account.xml, app/src/main/res/layout/fragment_report_statuses.xml, app/src/main/res/layout/fragment_search.xml, app/src/main/res/layout/fragment_timeline.xml, app/src/main/res/layout/fragment_timeline_notifications.xml, app/src/main/res/layout/fragment_trending_links.xml, app/src/main/res/layout/fragment_trending_tags.xml, app/src/main/res/layout/item_conversation.xml
Display normal Android (i.e., fading) scrollbars when the user scrolls in lists.
=> feat: Show vertical scrollbars on scrollable lists

app/src/main/java/app/pachli/BottomSheetActivity.kt, app/src/main/java/app/pachli/components/accountlist/AccountListFragment.kt, app/src/main/java/app/pachli/components/instancemute/fragment/InstanceListFragment.kt, app/src/main/java/app/pachli/components/notifications/NotificationsViewModel.kt, app/src/main/java/app/pachli/components/report/adapter/StatusesPagingSource.kt, app/src/main/java/app/pachli/components/scheduled/ScheduledStatusPagingSource.kt, app/src/main/java/app/pachli/components/search/adapter/SearchPagingSource.kt, app/src/main/java/app/pachli/di/NetworkModule.kt, app/src/main/java/app/pachli/network/MastodonApi.kt, app/src/main/java/app/pachli/usecase/TimelineCases.kt, app/src/test/java/app/pachli/BottomSheetActivityTest.kt, app/src/test/java/app/pachli/components/notifications/NotificationsViewModelTestNotificationAction.kt, gradle/libs.versions.toml
Remove the rxjava3 `Single` type from the MastodonAPI definition, replacing with `Response` or `NetworkResult` as appropriate.
Update callsites and tests as appropriate.
This removes the need for `com.squareup.retrofit2:adapter-rxjava3`
=> refactor: Remove rxjava3 from Mastodon API spec

app/src/main/java/app/pachli/components/accountlist/AccountListFragment.kt
The previous code ran the API call in a `try/catch block`, and handled errors in the `catch`. But `NetworkResult` already catches the exception and transforms it to a failure, so the error case was not handled.
Replace with `NetworkResult.fold`.
=> fix: Improve error handling when blocking accounts

app/lint-baseline.xml, app/src/main/java/app/pachli/components/timeline/CachedTimelineRepository.kt, app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/CachedTimelineRemoteMediator.kt, app/src/main/java/app/pachli/db/AppDatabase.kt
The previous code did not always work when the user returned to the app after a lengthy absence (e.g., overnight).
Instead of restoring by scrolling in `TimelineFragment`, restore by working with the platform.
Determine the initial page to fetch by looking half a page ahead of the saved saved status ID, and fetch that status and the page immediately prior. This seems to match the view's expectations about what will be immediately available.
Set `jumpThreshold` and `enablePlaceholders` in the `PagingConfig` so the paging system will jump to the saved status.
Remove the restoration code in `TimelineFragment`.
Fixes #53
=> fix: Restore the user's reading position under all circumstances

.github/workflows/upload-orange-release-google-play.yml
Previous configuration only fetched the most recent revision. Since the `orangeRelease` `versionCode` is calculated from the number of previous revisions this always set the `versionCode` to 1.
Fetch all revisions to avoid this.
=> ci: Fetch all revisions to calculate correct versionCode

app/src/test/java/app/pachli/MainActivityTest.kt, app/src/test/java/app/pachli/components/compose/ComposeActivityTest.kt, app/src/test/java/app/pachli/di/FakeMastodonApiModule.kt
Extract `FakeMastodonApiModule` from `ComposeActivityTest` to make it usable in other tests. Update `MainActivityTest` to use the extracted code.
=> refactor: Extract FakeMastodonApiModule

app/src/test/java/app/pachli/components/notifications/NotificationsViewModelTestBase.kt, app/src/test/java/app/pachli/components/notifications/NotificationsViewModelTestStatusDisplayOptions.kt, app/src/test/java/app/pachli/components/notifications/NotificationsViewModelTestUiState.kt, app/src/test/java/app/pachli/components/timeline/CachedTimelineViewModelTestBase.kt, app/src/test/java/app/pachli/components/timeline/CachedTimelineViewModelTestStatusDisplayOptions.kt, app/src/test/java/app/pachli/components/timeline/CachedTimelineViewModelTestUiState.kt, app/src/test/java/app/pachli/components/timeline/NetworkTimelineViewModelTestBase.kt, app/src/test/java/app/pachli/components/timeline/NetworkTimelineViewModelTestStatusDisplayOptions.kt, app/src/test/java/app/pachli/components/timeline/NetworkTimelineViewModelTestUiState.kt, app/src/test/java/app/pachli/fakes/InMemorySharedPreferences.kt
Previously the tests mocked shared preferences with a map and a mock that had to be implemented for each test that needed it.
Replace this with `InMemorySharedPreferences`, which provides the normal `SharedPreferences` interface so can be used as a drop-in replacement.
=> refactor: Replace test preference mocks with InMemorySharedPreferences

app/src/main/java/app/pachli/components/viewthread/ViewThreadViewModel.kt, app/src/test/java/app/pachli/components/viewthread/ViewThreadViewModelTest.kt
Instead of calling the filters API directly use `FiltersRepository` to handle the v1/v2 filter differences.
=> refactor: Update ViewThreadViewModel to use FiltersRepository

app/lint-baseline.xml, app/src/main/java/app/pachli/util/LinkHelper.kt, app/src/main/java/app/pachli/view/GraphView.kt, app/src/main/res/drawable/conversation_thread_line.xml, app/src/main/res/drawable/status_divider.xml, app/src/main/res/layout/item_status_detailed.xml, app/src/main/res/values-night/theme_colors.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/theme_colors.xml
Use the Material colour for `conversation_thread_line` (which is `colorOutlineVariant`) instead of a custom attribute.
Elsewhere, use the Material attribute directly (in code), or replace the custom divider with a `MaterialDivider`.
This makes some colour definitions unused, so remove them.
Fixes #148
=> fix: Show thread indicators and other dividers using Material colours

plugins/markdown2resource/settings.gradle
Create a settings.gradle file so it is treated as a separate project.
=> change: Mark markdown-plugin as a distinct project

app/src/main/AndroidManifest.xml, app/src/main/java/app/pachli/service/SendStatusService.kt
Android 14 (SDK 34) requires a `foregroundServiceType` and `onTimeout()` implementation for foreground services, otherwise creating the service will crash.
Do this. If `SendStatusService` does timeout then any pending statuses are marked as failed, saved to drafts, and the user is informed.
Fixes #162
=> fix: Add foregroundServiceType/onTimeout() to prevent crash

app/src/main/java/app/pachli/fragment/ViewImageFragment.kt, app/src/main/java/app/pachli/fragment/ViewMediaFragment.kt, app/src/main/java/app/pachli/fragment/ViewVideoFragment.kt
Previous code finalised the view setup in `onViewCreated`, so if you opened some media, switched away from the app, and switched back you'd get a blank screen.
Fix this by doing the finalisation in `onResume()`, so the media is displayed correctly when returning to the fragment.
Fixes #161
=> fix: Show media when resuming ViewMediaFragment

.gitignore
Ignore directories created by `gradle-profiler`.
=> chore: Update .gitignore for gradle-profiler

app/src/main/java/app/pachli/fragment/ViewImageFragment.kt, app/src/main/java/app/pachli/fragment/ViewMediaFragment.kt, app/src/main/java/app/pachli/fragment/ViewVideoFragment.kt, app/src/main/java/app/pachli/pager/SingleImagePagerAdapter.kt
Previous code had to distinguish between showing an attachment or
showing an image by URL.
Simplify this by -- in the image URL case -- creating a fake attachment
that references the image URL.
Move the code that unmarshalls the Bundle arguments to
`ViewMediaFragment` to share between `ViewImageFragment` and
`ViewVideoFragment`.
=> refactor: Simplify View{Image,Media,Video}Fragment creation

app/src/main/java/app/pachli/util/StatusDisplayOptionsRepository.kt
The previous code didn't include SHOW_CARDS_IN_TIMELINES in the list of prefkeys that change `StatusDisplayOptions`, so changing the preference wouldn't update the timeline display; you had to close/restart the app.
=> fix: Update timeline when link preview setting changes

app/build.gradle, build.gradle, gradle/libs.versions.toml
This removes all use of kapt from the project.
=> refactor: Use ksp instead of kapt for Hilt

app/src/main/java/app/pachli/fragment/ViewVideoFragment.kt
Previously, playing a video would show the controls and associated overlay for five seconds before fading them out. This obscures the video for too long.
Fix this by:
- Only showing the media description on start, and remove after two seconds
- Show the controls (and media description) if the user taps, removing after two seconds
- Pausing the video (with the pause control, or tapping on the media description) keeps the controls and description on-screen indefinitely so they are easier to read
Fixes #144
=> fix: Adjust video playback UX behaviour

app/src/main/java/app/pachli/components/compose/ComposeAutoCompleteAdapter.kt, app/src/main/java/app/pachli/components/compose/MediaUploader.kt, app/src/main/java/app/pachli/components/login/LoginWebViewActivity.kt, app/src/main/java/app/pachli/components/notifications/NotificationsViewModel.kt, app/src/main/java/app/pachli/components/timeline/FiltersRepository.kt, app/src/main/java/app/pachli/components/timeline/TimelineKind.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt, app/src/main/java/app/pachli/components/trending/viewmodel/TrendingLinksViewModel.kt, app/src/main/java/app/pachli/util/Resource.kt, app/src/main/java/app/pachli/viewdata/TrendingViewData.kt
Using a sealed interface (instead of a sealed class) at the root of the hierarchy avoids the overhead of having to create and initialise the class (visible in the generated bytecode).
It also makes the instantiation code slightly less cumbersome because the code doesn't need to pass parameters to the root's constructor.
=> refactor: Use sealed interfaces for lighterweight code

app/src/main/java/app/pachli/components/preference/TabFilterPreferencesFragment.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt, app/src/main/java/app/pachli/settings/SettingsConstants.kt, app/src/main/res/values/strings.xml
Some Mastodon posters have a annoying habit of boosting their own posts some time after they've posted them. 
Some people got fed up , TL became disorganized due to this.
No need to see the same toot over and over again.
- Add an additional option to the "Filters > Tabs" preference to show these self-boosts (default: on)
***screen of "Filters > Tabs" preference***
before | after
:--: | :--:
| ![image](https://github.com/pachli/pachli-android/assets/62137820/e34e4620-3852-4f46-9663-bf1046f35e5f) |![image](https://github.com/pachli/pachli-android/assets/62137820/6d462fce-b746-4aeb-8c29-c7c5f157efb9)
***screen of Home Timeline***
***switch-on(self-boosts are displayed)*** | ***swith-off(self-boosts are not displayed)***
:--: | :--:
| …
=> feat: Put option to hide self-boosts in preference (#39)

app/src/main/res/values/strings.xml
Previous code called filters that affect threads "Conversations". Correct this to "Threads", to distinguish from "Direct Messages" which can also be known as "conversations" (in the API in particular).
=> fix: Use the correct name for filters affecting threads

app/src/main/res/values-it/strings.xml
This string is missing inside values-it, but it is present in values-en, let's add it too and translate it.
=> fix(l10n): Update Italian translations

app/lint-baseline.xml, app/src/main/java/app/pachli/components/filters/EditFilterViewModel.kt, app/src/main/java/app/pachli/components/filters/FiltersViewModel.kt, app/src/main/java/app/pachli/components/notifications/NotificationsViewModel.kt, app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/CachedTimelineViewModel.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/NetworkTimelineViewModel.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt, app/src/main/java/app/pachli/components/viewthread/ViewThreadViewModel.kt, app/src/main/java/app/pachli/network/FilterModel.kt, app/src/test/java/app/pachli/FilterV1Test.kt, app/src/test/java/app/pachli/components/notifications/NotificationsViewModelTestBase.kt, app/src/test/java/app/pachli/components/timeline/CachedTimelineViewModelTestBase.kt, app/src/test/java/app/pachli/components/timeline/NetworkTimelineViewModelTestBase.kt, app/src/test/java/app/pachli/components/viewthread/ViewThreadViewModelTest.kt
This previous code could crash if `filterModel.kind` (marked `lateinit`) had not been set before the filters are loaded. This could happen in rare cases.
Fix this by rewriting `FilterModel`. Instead of creating a half-empty object that still needs further initialisation, delay the creation until all the necessary information is available, and pass it in the `FilterModel` constructor.
This also forces code that uses `FilterModel` to properly handle the case where it might be null at the point where filtering decisions have to be made.
This means that `TimelineViewModel` (and subclasses) no longer need the `init()` function to complete their construction, which was another significant code smell. Pass the `TimelineKind` to the view models via their `SavedStateHandle`.
This showed that …
=> fix: Prevent potential crash when filters are slow to load

app/src/main/java/app/pachli/fragment/ViewImageFragment.kt
Previously, ending a drag on an image (that didn't result in dismissing the fragment) animates the image back in to position restoring the X axis scale factor.
The Y axis scale factor was not restored, potentially breaking the image's aspect ratio. Restore the Y axis scale factor to fix this (`ViewVideoFragment` already handles this correctly).
Fixes #202
=> fix: Restore image aspect ratio when drag ends

app/build.gradle, docs/contributing/code.md
There's a well-hidden `updateLintBaseline` task that does what the custom `newLintBaseline` task does. Prefer the `update...` task to reduce the amount of custom machinery in this build.
=> build: Use `updateLintBaseline` task

app/src/main/res/values/strings.xml
"level" is the term used throughout Android documentation.
Originally submitted by https://github.com/chaoscalm
=> fix: Refer to "SDK level" rather than "SDK version"

app/lint-baseline.xml, app/src/main/java/app/pachli/components/account/media/AccountMediaFragment.kt, app/src/main/java/app/pachli/components/conversation/ConversationsFragment.kt, app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt, app/src/main/res/layout-sw640dp/fragment_timeline.xml, app/src/main/res/layout/fragment_timeline.xml
Previously the middle-of-screen progress spinner and the spinner that appears on a swipe-to-refresh could get out of sync.
Fix this by removing the middle-of-screen progress spinner from relevant fragments, as the swipe-to-refresh spinner shows the user that an operation is in progress, and also clues them in to the fact that a swipe-to-refresh is possible (by using the common UX control).
Fixes #75
=> fix: Remove progressbar from status timelines

app/src/main/res/values-v29/themes.xml, app/src/main/res/values/styles.xml
Previous code always set `navigationBarColor` and `statusBarColor` to `transparent` irrespective of the API level.
This only works on API 29 and above; if you do it on API levels lower than that the system navigation buttons (home, back, recents) are typically shown on a very similar colour to the background, making them very hard to see.
Fixes #221
=> fix: Ensure system controls are visible on older devices

app/src/main/java/app/pachli/util/SharedPreferencesRepository.kt
The preference change listener was being optimised out by R8, causing rapid garbage collection, breaking the `changes` flow in release builds.
Fix this by annotating the field with `@Keep` so it is retained.
Fixes #225
=> fix: Show preference changes immediately

.github/workflows/ci.yml, .github/workflows/populate-gradle-build-cache.yml, .github/workflows/upload-blue-release-google-play.yml, .github/workflows/upload-orange-release-google-play.yml, app/build.gradle, app/src/fdroid/kotlin/app/pachli/di/UpdateCheckModule.kt, app/src/fdroid/kotlin/app/pachli/updatecheck/FdroidService.kt, app/src/fdroid/kotlin/app/pachli/updatecheck/UpdateCheck.kt, app/src/fdroid/res/values/strings.xml, app/src/github/kotlin/app/pachli/di/UpdateCheckModule.kt, app/src/github/kotlin/app/pachli/updatecheck/GithubService.kt, app/src/github/kotlin/app/pachli/updatecheck/UpdateCheck.kt, app/src/github/res/values/strings.xml, app/src/google/kotlin/app/pachli/di/UpdateCheckModule.kt, app/src/google/kotlin/app/pachli/updatecheck/UpdateCheck.kt, app/src/google/res/values/strings.xml, app/src/main/java/app/pachli/MainActivity.kt, app/src/main/java/app/pachli/components/preference/PreferencesFragment.kt, app/src/main/java/app/pachli/settings/SettingsConstants.kt, app/src/main/java/app/pachli/updatecheck/UpdateCheck.kt, app/src/main/res/values/donottranslate.xml, app/src/main/res/values/string-arrays.xml, app/src/main/res/values/strings.xml, docs/contributing/code.md, gradle/libs.versions.toml
Users can inadvertently get stuck on older versions of the app; e.g., by installing from one F-Droid repository that stops hosting the app at some later time.
Analytics from the Play Store also shows a long tail of users who are, for some reason, on an older version.
On resuming `MainActivity`, and approximately once per day, check and see if a newer version of Pachli is available, and prompt the user to update by going to the relevant install location (Google Play, F-Droid, or GitHub).
The dialog prompt allows them to ignore this specific version, or disable all future update notifications. This is also exposed through the preferences, so the user can adjust it there too.
A different update check method is used for each installation location.
- F-Droid: Use the F-Droid API to query for …
=> feat: Periodically check for updates and alert user

app/build.gradle
Now that the flavour includes the store name it's not sufficient to check for "orange" as the flavour, as that no longer matches. Now it must start with "orange" to trigger using the git commit count as the version code.
=> ci: Use correct versionCode for orange.* versions

app/proguard-rules.pro
Without this the model classes are not retained, which causes a `ClassCastException` when parsing the new models for the instance v1 and instance v2 API calls.
Fixes #250
=> fix: Keep network model classes, preventing crash on startup

app/src/main/java/app/pachli/components/conversation/ConversationsFragment.kt, app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt, app/src/main/java/app/pachli/components/viewthread/ViewThreadFragment.kt, app/src/main/java/app/pachli/fragment/SFragment.kt
Not all subclasses were calling `super.onViewCreated()` so collecting the server capability wasn't happening consistently. Fix this, and add a `@CallSuper` annotation to prevent the problem from recurring.
=> fix: Collect the server capabilities in SFragment subclasses

app/lint-baseline.xml, app/src/main/AndroidManifest.xml, app/src/main/res/values-v29/themes.xml, app/src/main/res/values/styles.xml
`Theme.Pachli` was being overriden on v29+ devices which meant that poll options were showing with too much padding. Fix that by using `AppTheme` as the final theme, and basing that off `Theme.Pachli`.
Black themes were using dark grey for toolbar and tab backgrounds, so fix that too for a seamless experience with the black theme.
=> fix: Update themes to correct poll/black theme issues

app/src/main/res/layout/item_status_edit.xml
Viewing edited statuses could crash on API levels around 26 with a ResourceNotFoundException. Using `?colorOutline` for the divider colour instead of `?android:textColorPrimary` fixes this, and is also a better colour to use.
=> fix: Prevent colour related crash on API level ~ 26

app/src/fdroid/kotlin/app/pachli/updatecheck/FdroidService.kt, app/src/github/kotlin/app/pachli/updatecheck/GithubService.kt
Prevents a crash if Proguard optimises them away in release builds.
=> fix: Ensure update-related data classes are retained

app/src/main/java/app/pachli/MainActivity.kt, app/src/main/java/app/pachli/PachliApplication.kt, app/src/main/java/app/pachli/settings/SettingsConstants.kt, app/src/main/java/app/pachli/usecase/DeveloperToolsUseCase.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values/strings.xml
Upgrading to this version of Pachli may trigger an Android bug where cached animation specifications are not cleared, resulting in incorrect animations (e.g., when navigating between activities).
This is an Android bug triggered by the Android Material library, https://github.com/material-components/material-components-android/issues/3644.
Show the user a dialog (once) when launching after an upgrade, so they know to restart their device if necessary.
=> feat: Warn the user about an Android animation bug

app/src/main/res/layout/preview_card.xml
Show up to two lines of the link's title and three lines of the link's description in link preview cards. This provides additional useful context to the user, especially when many links bury the important information at the end of the title.
=> feat: Increase the amount of information in link previews

app/src/main/java/app/pachli/StatusListActivity.kt
Display the "compose" FAB when viewing a favourite list. 
Tapping the button will open the `ComposeActivity` for creating new toot.
Before | After
:--: | :--:
|![image](https://github.com/pachli/pachli-android/assets/62137820/40d4446a-4c35-407d-8537-19224ba9e6a6)|![image](https://github.com/pachli/pachli-android/assets/62137820/093b1355-2ce6-4d0e-8f81-77b5a7eb5a53)
Fixes #229
=> feat: Display compose button when viewing favorites list

app/src/main/java/app/pachli/adapter/StatusBaseViewHolder.kt, app/src/main/java/app/pachli/util/CompositeWithOpaqueBackground.kt
Quoting @connyduck in https://github.com/tuskyapp/Tusky/pull/4150:
"""
The transformation ends up in Glide's memory cache and leaks whole Activities through the view -> context reference.
This fixes the problem by removing the background detection logic (so the view reference is no longer needed) and setting the background directly instead. Looks exactly as before.
"""
Co-authored-by: Konrad Pozniak <opensource@connyduck.at>
=> fix: Prevent memory leak in CompositeWithOpaqueBackground

app/src/main/java/app/pachli/BaseActivity.kt, app/src/main/java/app/pachli/PachliApplication.kt, app/src/main/java/app/pachli/components/compose/ComposeActivity.kt, app/src/main/java/app/pachli/components/preference/PreferencesActivity.kt, app/src/main/java/app/pachli/components/preference/PreferencesFragment.kt, app/src/main/java/app/pachli/util/ThemeUtils.kt, app/src/main/res/values/string-arrays.xml, core/preferences/src/main/kotlin/app/pachli/core/preferences/SettingsConstants.kt
Previous code treated the app theme as a mix of strings and enums. Convert to exclusively use the `AppTheme` enum to improve type safety.
=> refactor: Use AppTheme enum exclusively

app/src/main/java/app/pachli/components/account/AccountActivity.kt, app/src/main/java/app/pachli/components/account/AccountViewModel.kt, app/src/main/res/drawable/profile_role_badge.xml, app/src/main/res/layout/activity_account.xml, app/src/main/res/values/dimens.xml, core/network/src/main/kotlin/app/pachli/core/network/model/Account.kt
Roles for the logged in user appeared in Mastodon 4.0.0 and can be displayed on the user's profile screen.
Show them as chips, adjusting the display of the existing "Follows you" and "Bot" indicators to make allowances for this.
Roles can have a custom colour assigned by the server admin. This is blended with the app colour so it is not too jarring in the display.
See also https://github.com/tuskyapp/Tusky/pull/4029
=> feat: Show roles on profiles

settings.gradle.kts
This should allow for periodic tracking of improvements (or regressions) in the build performance.
Fixes #314
=> build: Publish Gradle buildscans when CI variable is non-empty

app/lint-baseline.xml, app/src/main/java/app/pachli/components/compose/ComposeActivity.kt, app/src/main/java/app/pachli/components/compose/dialog/AddPollOptionsAdapter.kt, app/src/test/java/app/pachli/SpanUtilsTest.kt, app/src/test/java/app/pachli/components/compose/ComposeActivityTest.kt, app/src/test/java/app/pachli/components/compose/MastodonLengthFilterTest.kt, app/src/test/java/app/pachli/components/compose/StatusLengthTest.kt, core/common/src/main/kotlin/app/pachli/core/common/string/StringUtils.kt, core/testing/lint-baseline.xml, core/testing/src/main/kotlin/app/pachli/core/testing/fakes/FakeSpannable.kt
Mastodon counts post lengths by considering emojis to be single characters, no matter how many unicode code points they are composed of. So "😜" has length 1.
Pachli was using `String.length`, which considers "😜" as length 2.
Correct the calculation by using a BreakIterator to count the characters in the string, which treats multi-character emojis as a length 1.
Poll options had a similar problem, exacerbated by the Mastodon web UI also having the same problem, see https://github.com/mastodon/mastodon/issues/28336.
Fix that by creating `MastodonLengthFilter`, an `InputFilter` that does the right thing for regular text that may contain emojis.
See also https://github.com/tuskyapp/Tusky/pull/4152, which has the fix for status length but not polls.
=> fix: Calculate length of posts and polls with emojis correctly

app/build.gradle.kts, app/src/blue/kotlin/app/pachli/CrashReporter.kt, app/src/main/java/app/pachli/PachliApplication.kt, app/src/main/res/values/strings.xml, app/src/orange/kotlin/app/pachli/CrashReporter.kt, build-logic/convention/src/main/kotlin/app/pachli/PachliFlavor.kt, gradle/libs.versions.toml
Add a dependency on ACRA (in orange builds only), and catch crashes.
The user is given the option to e-mail the crash report data to the support address, and can view and edit/redact the data before doing so.
=> feat: Allow the user to report crashes in orange builds

app/src/main/java/app/pachli/components/timeline/CachedTimelineRepository.kt, app/src/main/java/app/pachli/components/viewthread/ViewThreadViewModel.kt, app/src/main/java/app/pachli/viewdata/StatusViewData.kt, app/src/test/java/app/pachli/components/viewthread/ViewThreadViewModelTest.kt, core/database/src/main/kotlin/app/pachli/core/database/dao/TranslatedStatusDao.kt, core/database/src/main/kotlin/app/pachli/core/database/model/TranslatedStatusEntity.kt
If a status was part of a thread, and it was not the "detailed" status, and it had been translated, then the view data was marked as "show the translation". But the translation was not loaded, so the status content appeared as empty.
Fix that by loading the translated content of all statuses in the thead and ensure that the translated content is rendered.
Throw an `IllegalStateException` in debug builds to catch any future occurrences of this.
Fixes #281
=> fix: Show translated content when viewing a thread

app/src/main/java/app/pachli/components/account/AccountActivity.kt
e35fa1db inadvertently contained some left over debug code that treats non-bot accounts as bots (for displaying the bot badge) and vice versa.
Fixes #321
=> fix: Correctly show if an account is a bot or not

core/database/src/main/kotlin/app/pachli/core/database/model/TabData.kt
The previous code was serialising the `TabKind` enum without the `_`, so
when it was converted back to the enum name (which has a `_`) it failed
and immediately crashed.
Fixes #306
=> fix: Prevent a crash if trending tags, links, or statuses are added to tabs

core/database/src/main/kotlin/app/pachli/core/database/model/TabData.kt
Old versions of the preference value could have been serialised without the `_` in the name, so handle those specially.
Fixes #329
=> fix: Prevent crash if a trending tab is present

app/src/main/java/app/pachli/settings/AccountPreferenceDataStore.kt, app/src/test/java/app/pachli/components/timeline/CachedTimelineViewModelTestBase.kt, app/src/test/java/app/pachli/components/timeline/NetworkTimelineViewModelTestBase.kt, app/src/test/java/app/pachli/components/viewthread/ViewThreadViewModelTest.kt, app/src/test/java/app/pachli/di/FakeCoroutineScopeModule.kt, app/src/test/java/app/pachli/util/StatusDisplayOptionsRepositoryTest.kt
Previously some tests had to manually create dependencies (instead of injecting them) because the dependency required the `TestScope` `CoroutineScope` as one of its dependencies.
Resolve this with a `FakeCoroutineScopeModule` that provides `TestScope` as `@ApplicationScope`. The tests can now inject their dependencies, which will use `TestScope`.
To inject `AccountPreferenceDataStore` it has been updated to use the current active account when reading or writing preferences.
=> refactor: Provide TestScope as ApplicationScope in tests

app/proguard-rules.pro
Previous rule didn't consider a deeper package hierarchy, so the new NodeInfo classes were being removed by ProGuard.
=> fix: Prevent crash by keeping network.model.** classes

core/network/src/main/kotlin/app/pachli/core/network/model/TimelineAccount.kt
Commit 993b7469 inadvertently broke this by removing the @SerializedName annotation, so the user's display name was always null and the UI fell back to showing the username.
Fixes #371
=> fix: Show display name in timelines, not the username

app/lint-baseline.xml, app/src/main/java/app/pachli/components/trending/TrendingTagViewHolder.kt, app/src/main/java/app/pachli/view/GraphView.kt, app/src/main/res/layout-land/item_trending_cell.xml, app/src/main/res/layout/item_trending_cell.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/attrs_graphview.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
The previous code incorrectly showed the trending tag usage data twice next to the end of the trending tag lines, instead of one entry for the usage data and one entry for the account data.
Fix that.
As part of this fix change how the data is displayed. Instead of using two distinct `TextView`, fixed to the bottom end of the chart, draw the text directly on the chart. The text is accurately position so that it is next to the end of the relevant line. If both lines overlap the label positions are adjusted appropriately.
The chart now uses Pachli blue and orange for the line colours.
While doing this I discovered that the mechanism used to fall back to particular chart colours if none were specified was incorrect, so fix that too.
=> fix: Show correct trending tag values at the end of the chart lines

app/lint-baseline.xml, app/src/main/java/app/pachli/components/notifications/NotificationsFragment.kt, app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt, app/src/main/java/app/pachli/fragment/SFragment.kt, app/src/main/java/app/pachli/fragment/ViewVideoFragment.kt, app/src/main/java/app/pachli/network/ServerRepository.kt, app/src/main/res/values/styles.xml
Previous code would show errors when fetching server info but with no mechanism to retry the operation, so it would "stick" until the user restarted the app.
Fix this with a retry action.
While I'm here use styles to ensure that all snackbars are 5 lines max length and remove code that sets the length.
=> fix: Allow users to retry errors when fetching server info

.github/workflows/ci.yml, .github/workflows/ktlint.yml, .github/workflows/populate-gradle-build-cache.yml, .github/workflows/upload-blue-release-google-play.yml, .github/workflows/upload-orange-release-google-play.yml
gradle-build-action is deprecated, setup-gradle replaces it. Enable the new support for the configuration cache.
=> chore: Migrate from gradle-build-action to setup-gradle

docs/contributing/translate.md
The Weblate UI now includes components for the different Pachli modules, update the translation instructions to account for this.
=> docs: Update translation instructions with new modules

.github/ci-gradle.properties
Gradle configuration currently takes ~ 25s per invocation on CI, this should hopefully reduce that significantly.
=> ci: Enable Gradle configuration cache on CI

app/build.gradle.kts, app/lint-baseline.xml, app/proguard-rules.pro, app/src/main/java/app/pachli/PachliApplication.kt, core/activity/build.gradle.kts, core/activity/src/blue/kotlin/app/pachli/core/activity/CrashReporter.kt, core/activity/src/orange/kotlin/app/pachli/core/activity/CrashReporter.kt, core/activity/src/orange/kotlin/app/pachli/core/activity/RingBuffer.kt, core/activity/src/testOrange/kotlin/RingBufferTest.kt, gradle/libs.versions.toml
Release builds normally strip out all logging to reduce the number of disk writes and reduce UI jank.
These logs would still be useful in user error reports from orange builds. To preseve them:
- Implement a simple `RingBuffer`.
- Create `TreeRing`, a `Timber` `Tree` logger that logs to a `RingBuffer` instance in orange release builds.
- Create `TreeRingCollector`, called when ACRA reports are generated, which includes the contents of the ring buffer in the report.
- Enable desugaring to allow the use of java.time libraries on older Android versions.
- Disable ProGuard obfuscation of class names as the obfuscation adds additional de-obfuscation steps when handling error reports from users.
=> feat: Include extra logs in error reports from orange release builds

.github/workflows/ci.yml
Previous code used `pull_request:` which meant
`secrets.GRADLE_ENCRYPTION_KEY` was not available, so the configuration cache was not restored.
Use `pull_request_target` to give the workflow access to `secrets`, and explicitly downscope the permissions of `GITHUB_TOKEN` to read only.
=> ci: Make secrets available in CI workflow

checks/src/main/java/app/pachli/lint/checks/LintRegistry.kt, checks/src/main/resources/META-INF/services/com.android.tools.lint.client.api.IssueRegistry
Resolves a build-time warning:
```
app.pachli.lint.checks.LintRegistry ... does not specify a vendor;
see IssueRegistry#vendor
```
=> change: Provide a vendor property in LintRegistry

app/src/main/java/app/pachli/components/preference/PreferencesFragment.kt
Previously it was constrained to a single line, and would clip on narrow devices.
Fixes #436
=> fix: Allow HIDE_TOP_TOOLBAR preference text to wrap

app/src/main/java/app/pachli/receiver/UnifiedPushBroadcastReceiver.kt
UnifiedPush broadcasts are used to trigger fetching new notifications. Previously this was a normal one-time work request. Mark it as expedited to increase the likelihood it will run soon.
=> fix: Expedite notification fetches via UnifiedPush

core/network/src/main/kotlin/app/pachli/core/network/model/Card.kt, core/network/src/main/kotlin/app/pachli/core/network/model/TrendsLink.kt
Neither server type implements the Mastodon API correctly, see
- https://github.com/friendica/friendica/issues/13887
- https://git.pleroma.social/pleroma/pleroma/-/issues/3238
Prevent crashes when parsing their broken JSON by providing default values for properties they omit.
Fixes #433
=> fix: Prevent crashes with bugs in Friendica and Pleroma servers

app/src/main/java/app/pachli/components/notifications/NotificationHelper.kt
When the `Notification.Type` enum was moved to a separate module it resulted in exceptions trying to deserialize the enum:
```
java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = app.pachli.core.network.model.Notification$Type)
```
This happened in debug builds without Proguard, so not a minification or renaming issue.
Fix this by providing `putEnum`/`getEnum` extension functions on `Bundle` that store the enum's ordinal value and restore it from that.
=> fix: Don't crash when deserializing notification types

app/src/main/java/app/pachli/MainActivity.kt
Shortcuts were being updated using `MainActivity.this` as the `Context` and leaking in `ShortcutManagerCompat`. Use the application context to fix this.
=> fix: Prevent memory leak when updating shortcuts

app/src/main/java/app/pachli/MainActivity.kt, app/src/main/java/app/pachli/components/notifications/NotificationHelper.kt, app/src/main/java/app/pachli/service/PachliTileService.kt, core/navigation/src/main/kotlin/app/pachli/core/navigation/Navigation.kt
The previous code didn't clear the task stack or recreate `MainActivity` when the active user was changed.
So if the user was logged in with account A and used "Compose" from a notification sent to account B, the active account was switched to B but the UI chrome wasn't. After exiting `ComposeActivity` they would be looking at the timeline for account B but with a toolbar that showed account A.
Fix this by clearing the task stack and explicitly recreating `MainActivity` when forwarding intents to `ComposeActivity`.
=> fix: Show correct account/timeline when composing from notifications

app/src/test/java/app/pachli/StatusComparisonTest.kt, app/src/test/java/app/pachli/components/timeline/CachedTimelineRemoteMediatorTest.kt, app/src/test/java/app/pachli/components/timeline/StatusMocker.kt, core/network/src/main/kotlin/app/pachli/core/network/di/NetworkModule.kt, core/network/src/main/kotlin/app/pachli/core/network/json/DefaultIfNullAdapter.kt, core/network/src/main/kotlin/app/pachli/core/network/model/Attachment.kt, core/network/src/test/kotlin/app/pachli/core/network/json/DefaultIfNullTest.kt
The `x` and `y` properties in `Attachment.Focus` may be null (not documented as such, but observed in the wild).
Provide a `DefaultIfNull` adapter that can be applied to these to replace null values with a sensible default.
=> fix: Handle null properties in `Attachment.Focus`

app/src/main/java/app/pachli/components/viewthread/edits/ViewEditsAdapter.kt
The previous code was using a bold version of the default font for inserted text. So if the user had set a custom font it was being ignored.
Fix this by creating a bold version of the user's typeface.
Fixes #435
=> fix: Use the correct font when showing inserted text

app/src/main/res/layout/item_status.xml
If the user increases the font size the labels for post statistics (number of replies, etc) can crash in to each other.
To give more space for the text:
- Shrink the label font size
- Move the labels slightly left / tighter to the icon
- Allow the "bookmark" icon to move next to the "more" icon. There's still 48dp of space for them, and this gives a little more space to the other icons that have labels
=> fix: Improve legibility of stats labels for large font sizes

core/network/src/main/kotlin/app/pachli/core/network/Server.kt, core/network/src/test/kotlin/app/pachli/core/network/ServerTest.kt
Firefish doesn't support the filters API, so remove filters from the list of capabilities.
Fixes #248
=> fix: Remove filters from Firefish capabilities

app/src/fdroid/kotlin/app/pachli/updatecheck/UpdateCheck.kt, app/src/github/kotlin/app/pachli/updatecheck/UpdateCheck.kt, app/src/google/kotlin/app/pachli/updatecheck/UpdateCheck.kt, app/src/main/java/app/pachli/MainActivity.kt, app/src/main/java/app/pachli/components/preference/PreferencesFragment.kt, app/src/main/java/app/pachli/updatecheck/UpdateCheck.kt, app/src/main/res/values/strings.xml, core/preferences/src/main/kotlin/app/pachli/core/preferences/SharedPreferencesRepository.kt
Add an additional preference entry that triggers an update when tapped. It also displays the earliest time of the next automatic update check as the preference summary.
Move the code that performs the update check (and the logic for whether to perform the check) out of `MainActivity` and in to `UpdateCheck` so it's available from `PreferencesFragment`.
=> feat: Allow the user to trigger update checks

app/lint-baseline.xml, app/src/main/java/app/pachli/adapter/StatusBaseViewHolder.kt, app/src/main/java/app/pachli/components/account/media/AccountMediaGridAdapter.kt, core/designsystem/src/main/res/values/dimens.xml, core/network/src/main/kotlin/app/pachli/core/network/model/Attachment.kt
Previous code showed a generic placeholder for audio media on the account's "Media" tab.
Fix this so the preview image is shown (if it's available).
- Move the "is this attachment previewable?" code to `Attachment` so it can be reused here.
- Restructure the logic in `AccountMediaGridAdapter` to use the new `isPreviewable()` method when deciding whether to show a preview.
- Attachments have dedicated placeholder drawables, use those when the preview is not available.
=> fix: Show previews for playable audio media from accounts

app/src/main/java/app/pachli/components/compose/ComposeViewModel.kt, core/common/src/main/kotlin/app/pachli/core/common/extensions/EnumExtensions.kt, core/database/src/main/kotlin/app/pachli/core/database/Converters.kt, core/network/src/main/kotlin/app/pachli/core/network/di/NetworkModule.kt, core/network/src/main/kotlin/app/pachli/core/network/json/HasDefault.kt, core/network/src/main/kotlin/app/pachli/core/network/model/Attachment.kt, core/network/src/main/kotlin/app/pachli/core/network/model/Filter.kt, core/network/src/main/kotlin/app/pachli/core/network/model/Notification.kt, core/network/src/main/kotlin/app/pachli/core/network/model/Status.kt, core/network/src/main/kotlin/app/pachli/core/network/model/TrendsLink.kt, core/network/src/test/kotlin/app/pachli/core/network/json/HasDefaultTest.kt
Previous code expected all incoming enums values to map directly to Kotlin enum constants.
This is a problem for servers with additional features -- e.g., "reaction" as a notification type.
Fix this with a new Moshi adapter that will set the incoming value to a given constant if it's not recognised.
Apply this to the enum constants in core.network to ensure they are handled.
Clean up enum handling in Converters.kt, ComposeViewModel.kt, and Status.kt by using the existing `.ordinal` property and some extension functions for idiomatic code.
Fixes #461
=> fix: Handle JSON enums with unknown values

app/src/main/java/app/pachli/components/timeline/CachedTimelineRepository.kt, app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt
A user is reporting that a refresh is happening in the middle of loading content, borne out by the existing logs.
Those logs don't say what has triggered the refresh attempt, so add additional logging whenever a refresh can occur to record what triggered it.
=> change: Log the trigger for a refresh/reload

app/src/main/java/app/pachli/StatusListActivity.kt, app/src/main/java/app/pachli/appstore/Events.kt, app/src/main/java/app/pachli/components/filters/EditFilterActivity.kt, app/src/main/java/app/pachli/components/filters/EditFilterViewModel.kt, app/src/main/java/app/pachli/components/filters/FiltersAdapter.kt, app/src/main/java/app/pachli/components/filters/FiltersViewModel.kt, app/src/main/java/app/pachli/components/notifications/NotificationsViewModel.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt, app/src/main/java/app/pachli/components/trending/viewmodel/TrendingTagsViewModel.kt, app/src/main/java/app/pachli/components/viewthread/ViewThreadViewModel.kt, app/src/main/java/app/pachli/network/FilterModel.kt, app/src/test/java/app/pachli/FilterV1Test.kt, core/network/src/main/kotlin/app/pachli/core/network/di/NetworkModule.kt, core/network/src/main/kotlin/app/pachli/core/network/json/EnumConstantConverterFactory.kt, core/network/src/main/kotlin/app/pachli/core/network/model/Filter.kt, core/network/src/main/kotlin/app/pachli/core/network/model/FilterContext.kt, core/network/src/main/kotlin/app/pachli/core/network/model/FilterV1.kt, core/network/src/main/kotlin/app/pachli/core/network/retrofit/MastodonApi.kt, core/network/src/test/kotlin/app/pachli/core/network/json/EnumConstantConverterFactoryTest.kt
A filter's context (previously referred to as its `kind`) controls where the filter is applied.
This was implemented as an enum with a specific property to control how it would serialise when @FormUrlEncoded, and with a @Json annotation for Moshi.
In addition, the model objects kept the filter context in its string form throughout Pachli, requiring periodic conversion to/from the enum type, making the code more complicated.
Fix this, by:
1. Converting the incoming JSON value to the enum type immediately, so the rest of the code uses the enum constants exclusively.
2. Implement a Retrofit converter that serialises the enum value when @FormUrlEncoded to the same string used in JSON serialisation
=> refactor: Remove duplicate strings from Filter contexts

app/build.gradle.kts, build-logic/convention/src/main/kotlin/app/pachli/KotlinAndroid.kt, core/activity/build.gradle.kts, core/data/src/test/kotlin/app/pachli/core/data/repository/InstanceInfoRepositoryTest.kt, core/database/build.gradle.kts, feature/about/build.gradle.kts
Once desugaring is enabled it needs to be enabled for up/down the dependency chain, so enable it in the shared configuration defined by the build convention code.
Highlighted a failing test that wasn't being run, so fix that too.
=> refactor: Enable core library desugaring as build convention logic

app/src/main/java/app/pachli/StatusListActivity.kt, app/src/main/java/app/pachli/components/filters/EditFilterViewModel.kt, core/network/src/main/kotlin/app/pachli/core/network/model/Filter.kt, core/network/src/main/kotlin/app/pachli/core/network/retrofit/MastodonApi.kt
Simplify code that users `Filter.Action` by deserialising directly into the type instead of storing / using strings throughout the API.
=> refactor: Remove duplicate strings from Filter.Action

app/src/main/java/app/pachli/components/compose/ComposeActivity.kt, app/src/main/java/app/pachli/components/compose/ComposeAutoCompleteAdapter.kt, app/src/main/java/app/pachli/components/compose/ComposeViewModel.kt, app/src/main/java/app/pachli/components/followedtags/FollowedTagsActivity.kt, app/src/main/java/app/pachli/components/followedtags/FollowedTagsViewModel.kt, app/src/test/java/app/pachli/components/compose/ComposeActivityTest.kt, core/network/src/main/kotlin/app/pachli/core/network/retrofit/MastodonApi.kt
The previous code used synchronous (i.e., non-suspending) functions to call the /api/v2/search and /api/v2/accounts/search endpoints.
This is not necessary as the search was always performed in a separate thread.
Remove, and replace their usage with the equivalent functions that suspend.
=> refactor: Remove synchronous search functions

app/src/main/java/app/pachli/ViewMediaActivity.kt, app/src/main/res/values/strings.xml
The previous code would share media by either:
a. If it was an image, downloading the image using Glide in to a bitmap, then recompressing as a PNG, saving, and sharing the resulting file.
b. Otherwise, create a temporary file, enqueue a DownloadManager request to download the media in to the file, and immediately start sharing, hoping that the download had completed in time.
Both approaches have problems:
In the "image" case the image was being downloaded (or retrieved from the Glide cache), decompressed to a bitmap, then recompressed as a PNG. This uses more memory, and doesn't share the original contents of the file. E.g., if the original file was a JPEG that's lost (and the PNG might well be larger than the source image).
In the second case the DownloadManager download is not …
=> fix: Ensure files are fully downloaded before sharing

app/lint-baseline.xml, build-logic/convention/src/main/kotlin/app/pachli/KotlinAndroid.kt, build-logic/convention/src/main/kotlin/app/pachli/PachliFlavor.kt, core/network/lint-baseline.xml, core/network/src/main/kotlin/app/pachli/core/network/Server.kt, core/testing/lint-baseline.xml, gradle/libs.versions.toml
New lint rules highlighted a potential crash; the use of named match groups (used here when extracting server versions) requires API >= 26 or throws an exception.
Use the group numbers instead of names when extracting the value, but keep the group names in the regular expressions for readability.
=> fix(deps): update agp to v8.3.0, lint to 31.3.0

app/src/main/java/app/pachli/ViewMediaActivity.kt, app/src/main/java/app/pachli/fragment/ViewImageFragment.kt, app/src/main/java/app/pachli/fragment/ViewMediaFragment.kt, app/src/main/java/app/pachli/fragment/ViewVideoFragment.kt, app/src/main/java/app/pachli/pager/ImagePagerAdapter.kt
Highlights:
- Implement fragment transitions for video to improve the UX, video won't start playing until the transition completes
- Remove rxJava
- Move duplicate code in to base classes
Details:
`MediaActionsListener`:
- Move to `ViewMediaFragment` as it's used by both subclasses
- Remove need for separate `VideoActionsListener`
- Rename methods to better reflect their purpose and improve readability
`ViewMediaFragment`:
- Move duplicated code from `ViewImageFragment` and `ViewVideoFragment`
- Rewrite code that handles fragment transitions to use a `CompleteableDeferred` instead of `BehaviorSubject` (removes rxJava).
- Rename methods and properties to better reflect their purpose and improve readability
- Add extra comments
`ViewImageFragment`:
- Rewrite code that handles fragment …
=> refactor: Restructure ViewMediaActivity and related fragments

app/src/main/java/app/pachli/MainActivity.kt, app/src/main/java/app/pachli/util/MediaUtils.kt
Previously a regular function launched with an rxJava scheduler, now it's a suspending function that enforces Dispatchers.IO as the context, launched in its own coroutine.
=> refactor: Implement deleteStaleCachedMedia as a suspending function

app/src/main/java/app/pachli/MainActivity.kt, app/src/main/java/app/pachli/util/ShareShortcutHelper.kt
Previously a regular function that created and subscribed to an rxJava callable, now it's a suspending function that enforces Dispatchers.IO as the context, launched in its own coroutine.
=> refactor: Implement updateShortcut as a suspending function

.github/workflows/apk-on-comment.yml
Debugging sometimes requires shipping APKs that have additional instrumentation to users.
It's bad practice to encourage users to install APKs that they have been given by a stranger on the Internet.
This new workflow will build a properly signed APK from a PR when a specific comment is added to the PR. After building a comment is added with a link to the workflow run and the URL the user can use to download the APK. This allows them to be sure that the APK contains only the code in the PR.
=> ci: Add workflow to build APK from PR

.github/workflows/upload-orange-release-google-play.yml
They're already compressed, and it slows down the workflow step.
=> ci: Don't compress APK files when uploading release artifacts

app/src/main/AndroidManifest.xml, app/src/main/java/app/pachli/MainActivity.kt, app/src/main/java/app/pachli/components/notifications/NotificationsActivity.kt, app/src/main/res/layout/activity_notifications.xml, core/navigation/src/main/kotlin/app/pachli/core/navigation/Navigation.kt
Previously the only way to access notifications was to dedicate a tab to them. Now notifications are available from the left-side navigation menu so they're always accessible.
Add them to the top of the list, and swap the order of bookmarks and favourites, assuming that users are more likely to want to see their bookmarks than their favourites.
Move "Edit profile" to the bottom with the other settings options, assuming that editing their profile does not happen very often, so should not be at the top of the list.
=> feat: Include "Notifications" in the left-side navigation menu

core/database/src/test/kotlin/app/pachli/core/database/dao/TimelineDaoTest.kt
The previous code forgot to close the DB after TimelineDaoTest was run, so a warning message was displayed when the test was run locally.
Therefore, solve this with closing the DB using the `@After` annotation.
Fixes #511
=> test: close DB in TimelineDaoTest

app/src/main/java/app/pachli/usecase/LogoutUsecase.kt, core/accounts/src/main/kotlin/app/pachli/core/accounts/AccountManager.kt
The account logout process could fail due to API exceptions; network errors for example, or if the user had already revoked the app's token for that account. This would prevent the rest of the logout process (cleaning database, etc) from completing.
Fix this by ignoring network errors during the logout process, and always cleaning up account content in the database.
Fix a related issue where a deleted account might be recreated in a partial state if the account's visible position was saved after it was deleted. The recreated account couldn't do anything as it had no tokens, but is very confusing.
=> fix: Ensure logging out accounts completes

app/src/main/java/app/pachli/fragment/ViewImageFragment.kt, app/src/main/java/app/pachli/fragment/ViewMediaFragment.kt, app/src/main/java/app/pachli/fragment/ViewVideoFragment.kt
When viewing an Image, it is not straightforward to understand that tapping on it will hide the toolbar and alt sheet, and those elements might get in the way of them viewing the full image.
Automatically hiding the toolbar and alt sheet after some short time might help the user two ways:
1. Get out of their way when they're viewing an image with an aspect ratio so that those elements are on top of it.
2. Showing them that those elements are hide-able, which might nudge into tapping to restore them and, consequently, learn about the "tap to hide/show" feature.
Interacting with the alt sheet cancels the auto-hide.
Fixes #505
=> feat: Auto-hide Image Viewer toolbar

app/src/main/java/app/pachli/components/account/media/AccountMediaFragment.kt, app/src/main/java/app/pachli/components/account/media/AccountMediaGridAdapter.kt, app/src/main/java/app/pachli/components/account/media/AccountMediaViewModel.kt, app/src/main/res/drawable/media_warning_bg.xml, app/src/main/res/layout/item_account_media.xml, core/activity/src/main/kotlin/app/pachli/core/activity/ImageLoadingHelper.kt, core/designsystem/src/main/res/values/dimens.xml
Previous code showed a small icon for account media that the user has hidden.
Now determine the correct size / aspect ratio for the media and use that to compute the placeholder (either a blurhash, or the link colour for consistency with the view on a timeline).
Fixes #513
=> fix: Show sized placeholder for hidden account media

app/src/main/java/app/pachli/TabPreferenceActivity.kt, app/src/main/java/app/pachli/components/viewthread/ViewThreadFragment.kt, app/src/main/res/layout/dialog_select_list.xml, app/src/main/res/layout/fragment_view_thread.xml, core/designsystem/src/main/res/values/styles.xml
Previous code used a normal ProgressBar and a coroutine to delay hiding/showing the bar for a snappier UI perception.
This is built-in functionality in LinearProgressIndicator, so switch to that.
While I'm here, implement the "Select list" dialog's layout as a layout resource.
=> refactor: Use LinearProgressIndicator with delayed show/hide

.gitignore
Ensures release build files are ignored irrespective of the build type.
=> chore: Ignore any files in app/*/release

app/src/main/java/app/pachli/MainActivity.kt, app/src/main/java/app/pachli/PachliApplication.kt, app/src/main/java/app/pachli/util/MediaUtils.kt, app/src/main/java/app/pachli/worker/PruneCachedMediaWorker.kt
Previous code would prune any cached media every time `MainActivity` was created, causing extra IO just as the user is trying to use the app.
Re-implement as a WorkManager worker so it can run when the device is idle, without interfering with the responsiveness of the device.
=> refactor: Prune cached media using a worker

settings.gradle.kts
Optimise the `repositories` declaration with a Gradle content filter that limits the `google()` repository to just Google artifacts. Results in a slight speedup when checking repositories, as the `google()` repository can be skipped when looking for non-Google artifacts.
=> chore: Only look for Google produced artifacts in Google repositories

app/src/main/java/app/pachli/ListsActivity.kt, app/src/main/java/app/pachli/viewmodel/ListsViewModel.kt, app/src/main/res/layout/dialog_list.xml, app/src/main/res/values/donottranslate.xml, app/src/main/res/values/strings.xml, core/data/src/main/kotlin/app/pachli/core/data/repository/ListsRepository.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/NetworkListsRepository.kt, core/network/src/main/kotlin/app/pachli/core/network/model/MastoList.kt, core/network/src/main/kotlin/app/pachli/core/network/retrofit/MastodonApi.kt
The replies policy controls whether replies from members of the list also appear in the list.
Display the replies policy as three radio buttons when a list is created or updated, and send the chosen replies policy via the API.
Default value if not specified is always "list", for consistency with the Mastodon API defaults.
While I'm here:
- Ensure the list dialog layout is inflated using the dialog's themed context
- Use a `TextInputLayout` wrapper around the list name in the list dialog for better UX
- Simplify the dialog layout, use LinearLayout, and standard padding and margins
=> feat: Allow the user to set a list's replies policy

app/src/main/java/app/pachli/fragment/SFragment.kt
For reasons not fully understood the root of a fragment's view might not have relevant view from the activity set as its parent. This causes `Snackbar.make()` to throw an exception, and crash.
See https://issuetracker.google.com/issues/228215869.
For now, "fix" this by swallowing the exception. Not showing the error is better than crashing.
=> fix: Catch and swallow snackbar exception

app/src/main/java/app/pachli/components/account/media/AccountMediaFragment.kt, app/src/main/java/app/pachli/components/accountlist/AccountListFragment.kt, app/src/main/java/app/pachli/components/announcements/AnnouncementsActivity.kt, app/src/main/java/app/pachli/components/conversation/ConversationsFragment.kt, app/src/main/java/app/pachli/components/drafts/DraftsActivity.kt, app/src/main/java/app/pachli/components/filters/FiltersActivity.kt, app/src/main/java/app/pachli/components/instancemute/fragment/InstanceListFragment.kt, app/src/main/java/app/pachli/components/notifications/NotificationsFragment.kt, app/src/main/java/app/pachli/components/scheduled/ScheduledStatusActivity.kt, app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt, app/src/main/java/app/pachli/components/trending/TrendingLinksFragment.kt, app/src/main/java/app/pachli/components/trending/TrendingTagsFragment.kt, app/src/main/java/app/pachli/components/viewthread/edits/ViewEditsFragment.kt, core/ui/src/main/kotlin/app/pachli/core/ui/BackgroundMessageView.kt, core/ui/src/main/kotlin/app/pachli/core/ui/extensions/ThrowableExtensions.kt, feature/lists/src/main/kotlin/app/pachli/feature/lists/AccountsInListFragment.kt, feature/lists/src/main/kotlin/app/pachli/feature/lists/ListsActivity.kt, feature/lists/src/main/kotlin/app/pachli/feature/lists/ListsForAccountFragment.kt
Previous code expected callers to typically provide the drawable and the error message string resource, resulting in duplicate code at many callsites.
Replace with three canned messages for empty containers, generic errors, and network errors respectively. The images for these are fixed, the caller may choose a different string resource for the error if there is a more specific option.
Update and simplify the call sites.
=> refactor: Simplify use of BackgroundMessageView

app/lint-baseline.xml, app/src/main/java/app/pachli/adapter/PollAdapter.kt, app/src/main/java/app/pachli/view/PollView.kt, app/src/main/java/app/pachli/viewdata/PollViewData.kt, app/src/main/res/drawable/poll_option_background_inset.xml, app/src/main/res/layout/item_poll.xml, app/src/main/res/layout/item_status.xml, app/src/main/res/layout/status_poll.xml, app/src/main/res/values/donottranslate.xml, app/src/main/res/values/strings.xml
Show a labelled checkbox to the bottom-right of polls that the user has not voted in and that have votes. If checked the current vote tally (as percentages) will be shown, along with a bar showing the relative value of each option.
=> feat: Allow user to see poll results before voting

core/common/src/main/kotlin/app/pachli/core/common/extensions/ViewBindingExtensions.kt
Based on Christophe Beyl's technique described in
https://bladecoder.medium.com/viewlifecyclelazy-and-other-ways-to-avoid-view-memory-leaks-in-android-fragments-4aa982e6e579
=> refactor: Simplify and optimize viewBinding delegate

app/src/main/java/app/pachli/components/account/media/AccountMediaRemoteMediator.kt, app/src/main/java/app/pachli/components/notifications/NotificationsViewModel.kt, app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/CachedTimelineRemoteMediator.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/NetworkTimelineRemoteMediator.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt, core/ui/build.gradle.kts, core/ui/src/main/kotlin/app/pachli/core/ui/extensions/ThrowableExtensions.kt, core/ui/src/main/res/values/strings.xml
Previous code would handle some expected exceptions (IO, HTTP) when fetching a timeline, and show them to the user. Any other exception would crash.
Now, surface all exceptions. Treat IO and HTTP exceptions as retryable and show the "Retry" option, all others are considered non-retryable.
Provide a specific error string for exceptions caused by bad JSON.
=> fix: Surface all exceptions to the user instead of crashing

app/src/main/java/app/pachli/util/ShareShortcutHelper.kt
Workaround a Glide bug where the error() handler is not always called, in this case when the URL does not resolve to an image; for example, a misconfigured server that redirects requests for the image to an HTML page.
Catch the exception and use the default avatar image in these cases.
=> fix: Don't crash on invalid avatars

app/src/main/java/app/pachli/components/filters/EditFilterActivity.kt, app/src/main/java/app/pachli/components/filters/EditFilterViewModel.kt, app/src/main/res/values/donottranslate.xml, app/src/test/java/app/pachli/FilterV1Test.kt, core/network/src/main/kotlin/app/pachli/core/network/retrofit/MastodonApi.kt
Mastodon API uses an "empty" `expires_in` value for a filter to mean "Does not expire" (i.e., indefinite).
This was modelled as a null. Which doesn't work, because Retrofit does not send name/value pairs in encoded forms if the value is null.
Fix this by making the API type a `String?`, and explicitly using the empty string when indefinite expiry is used. This has to be converted back to an Int? in a few places.
See https://github.com/mastodon/documentation/issues/1216#issuecomment-2030222940
=> fix: Allow filter expiration to be set to "indefinite"

app/src/main/java/app/pachli/MainActivity.kt
The compose button isn't initially working on `MainActivity`. It is only properly setup after changing tabs.
Fix by calling `MainActivity.refreshComposeButtonState(TabViewData)` on creation.
=> fix: Setup compose button when creating MainActivity

.github/actions/setup-build-env/action.yml
The new version bundles the wrapper validation action, so switch to that.
=> chore(deps): update gradle/actions digest to 6cec5d4

app/src/main/java/app/pachli/MainActivity.kt
https://github.com/pachli/pachli-android/pull/589 changed the initial setting of the action bar title to use `binding.mainToolbar.title` instead of `supportActionBar?.title`.
Not sure why, but this doesn't work on first use, and was showing "Pachli Current" until the user changes tabs. Swap one usage back to `supportActionBar?.title` to fix this, and update the other to do the same thing to keep the code consistent.
=> fix: Ensure actionbar title is set correctly

app/src/main/java/app/pachli/components/timeline/NetworkTimelineRepository.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/NetworkTimelinePagingSource.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/NetworkTimelineRemoteMediator.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/PageCache.kt, app/src/test/java/app/pachli/components/timeline/NetworkTimelinePagingSourceTest.kt, app/src/test/java/app/pachli/components/timeline/NetworkTimelineRemoteMediatorTest.kt
The PageCache implementation wasn't properly dealing with timelines that could return statuses in non-chronological order.
For example, if you bookmark a recent status, then go back in the timeline and bookmark an older status; the bookmarks timeline is ordered by the time of the bookmark event, not the creation time of the status that was bookmarked.
If a sufficiently old status was bookmarked so it straddled a page boundary you could have a situation where the range of status IDs in two different cached pages overlapped.
E.g., this log extract:
```
0: k: 110912736679636090, prev: 3521487, next: 3057175, size: 40, range: 112219564107059218..110912736679636090
1: k: 111651744569170291, prev: 3049659, next: 2710596, size: 40, range: 111926741634665808..111651744569170291
```
The range of …
=> fix: Update PageCache to handle non-chronological ordering

app/src/main/java/app/pachli/components/timeline/viewmodel/NetworkTimelineRemoteMediator.kt, app/src/main/java/app/pachli/components/trending/TrendingLinksRepository.kt, app/src/main/java/app/pachli/components/trending/viewmodel/TrendingTagsViewModel.kt, core/network/src/main/kotlin/app/pachli/core/network/retrofit/MastodonApi.kt
The previous code didn't set a limit for the number of posts, links, and hashtags to fetch on the trending pages, so used the conservative defaults.
Increase these to the API maximums to show the user more information.
=> feat: Fetch more trending posts, links, and hashtags

app/src/main/java/app/pachli/fragment/ViewVideoFragment.kt, app/src/main/res/layout/fragment_view_video.xml
Previous code didn't trigger the transition from `ViewMediaActivity` when playing a video until the video had loaded. If the connection was slow or had other issues this resulted in the video "sticking" in the timeline until it loaded.
Change this, and trigger the transition immediately.
Fixes #598
While looking at this:
- Save the play/pause state of the video during a swipe, pause the video, and restore the state when the swipe is cancelled.
- Transition the entire video view, to improve the animated transition back to the activity.
- Remove the custom progress spinner, use the one provided by the player.
- Display the player controller via the layout XML instead of code
=> fix: Improve transitions in/out of playing video

.github/workflows/apk-on-comment.yml
apk-on-comment checkout is failing on PRs from forked repositories, possibly because it can't find the ref.
Try and fix this by using the SHA when checking out.
=> ci: apk-on-comment: Checkout by SHA

app/src/main/java/app/pachli/components/account/AccountActivity.kt
AccountActivity is full screen, so the swipe spinner was appearing very close to the top system bar. Adjust the spinner's top margin to avoid the system bar, and have it scale in/out so it doesn't appear to slide out from an invisible barrier.
=> change: Move SwipeRefreshLayout margin in AccountActivity

app/src/main/java/app/pachli/adapter/ReportNotificationViewHolder.kt, app/src/main/java/app/pachli/components/compose/MediaUploader.kt, app/src/main/java/app/pachli/components/notifications/SeveredRelationshipsViewHolder.kt, app/src/main/java/app/pachli/components/notifications/StatusNotificationViewHolder.kt, checks/src/main/java/app/pachli/lint/checks/DateDotTimeDetector.kt, checks/src/main/java/app/pachli/lint/checks/LintRegistry.kt, checks/src/test/java/app/pachli/lint/checks/DateDotTimeDetectorTest.kt
Avoids unnecessary object creation.
Add a lint rule to catch this.
=> refactor: Prefer System.currentTimeMillis() to Date().getTime()

app/src/main/java/app/pachli/components/account/AccountActivity.kt
The change in 5959d23d resulted in a stuck margin when scrolling up in the account view.
Fix the `SwipeRefreshLayout` offset in a different way that doesn't have that problem; move the spinner's start position to the top of the screen (instead of the negative offset it normally has) and keep the same relative offset from the end position.
Have it scale in on the drag to complete the effect.
=> change: Adjust SwipeRefreshLayout offset in AccountActivity

app/src/main/java/app/pachli/components/conversation/ConversationsFragment.kt, app/src/main/java/app/pachli/components/notifications/NotificationsFragment.kt, app/src/main/java/app/pachli/util/ListStatusAccessibilityDelegate.kt
`ListStatusAccessiblityDelegate` was ignoring notifications because it was checking the status against the concrete `StatusViewData` and not the interface `IStatusViewData`.
Fix that and now notifications have accessibility actions.
`ConversationsFragment` didn't set the accessibility delegate, so no actions appeared. Fix that so they do.
=> fix: Enable talkback actions in notifications and conversations

app/src/main/res/layout/item_tab_preference.xml
Talkback was speaking it as "Unlabeled". It's not necessary for Talkback, as the tab name describes it in the list.
=> fix: Mark tab drag icon as unimportant for accessiblity

.github/workflows/ci.yml
Experiment to see if CI can run on release builds without a large performance impact.
=> ci: Run CI on release as well as debug builds

app/lint-baseline.xml, app/src/main/java/app/pachli/adapter/ReportNotificationViewHolder.kt, app/src/main/java/app/pachli/adapter/StatusBaseViewHolder.kt, app/src/main/java/app/pachli/components/compose/view/ComposeScheduleView.kt, app/src/main/java/app/pachli/components/notifications/StatusNotificationViewHolder.kt, app/src/main/java/app/pachli/components/viewthread/ConversationLineItemDecoration.kt, checks/src/main/java/app/pachli/lint/checks/ContextCompatGetDrawableDetector.kt, checks/src/main/java/app/pachli/lint/checks/LintRegistry.kt, checks/src/test/java/app/pachli/lint/checks/ContextCompatGetDrawableDetectorTest.kt
Replace `ContextCompat.getDrawable()`, as the app-compat version has platform fixes and backports.
appcompat-lint warns about bare `context.getDrawable()`, but does not cover `ContextCompat` (https://issuetracker.google.com/issues/337905331)
=> refactor: Use AppCompatResources.getDrawable()

app/src/main/java/app/pachli/adapter/PollAdapter.kt, app/src/main/java/app/pachli/components/viewthread/edits/ViewEditsAdapter.kt, app/src/main/java/app/pachli/viewdata/PollViewData.kt, app/src/main/res/layout/fragment_view_edits.xml, app/src/main/res/layout/item_poll.xml, core/network/src/main/kotlin/app/pachli/core/network/model/StatusEdit.kt
Edited polls only include the list of options with titles; no other metadata (poll ID, single/multiple choice, vote counts, etc). Since the data shape didn't match Moshi wasn't decoding the data.
Provide dedicated data classes to model the response, and add a fourth poll display option to represent viewing an edit history snapshot.
=> fix: Show edit history for status' with polls

app/src/main/java/app/pachli/MainActivity.kt, app/src/main/java/app/pachli/PachliApplication.kt, app/src/main/java/app/pachli/usecase/DeveloperToolsUseCase.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml, core/preferences/src/main/kotlin/app/pachli/core/preferences/SettingsConstants.kt
This warning (added in #274) includes a comment saying that we can remove it after 2024-03-01, so the time has come :)
I think it's worth mentioning that I've been seeing this warning on new installs of Pachli 2.4.0, even though the code suggests that the warning should only be shown following upgrades from previous versions. Seems like something to watch out for if we ever need to build similar behavior in the future.
=> remove: remove janky animation warning

app/src/main/java/app/pachli/EditProfileActivity.kt
Previous code didn't get the viewmodel to check if the content had changed, so `onBackPressedCallback` wasn't enabled, and the user could edit the bio and press "back" without being prompted to save their changes.
=> fix: Prompt user to save/discard changes after editing bio

app/src/main/java/app/pachli/util/ListStatusAccessibilityDelegate.kt
22729df1 broke accessiblity actions in non-notification timelines by returning too early if the status was not a NotificationViewData.
=> fix: Re-enable accessiblity actions in all timelines

app/src/fdroid/kotlin/app/pachli/updatecheck/UpdateCheck.kt, app/src/testFdroid/kotlin/app/pachli/updatecheck/UpdateCheckTest.kt
The F-Droid API can return a `suggestedVersionCode` that F-Droid has not successfully built (e.g., there was a network issue preventing F-Droid from fetching the source code at the time of the last build).
This meant users were being prompted to update when there was not a built package to update to.
Fix this by verifying that `suggestedVersionCode` appears in the list of packages. If it doesn't then fall back to the highest version code in the list of packages.
Fixes #684
=> fix: Only suggest upgrading to a version F-Droid has built

app/src/main/java/app/pachli/fragment/SFragment.kt, core/activity/src/main/kotlin/app/pachli/core/activity/extensions/ActivityExtensions.kt
Previous code always included the transitionKind enum as an extra, and could cause a crash if the activity launched by the intent was not a Pachli activity.
Fixes #700.
=> fix: Only include transitionKind in intents for Pachli activities

core/network/src/main/kotlin/app/pachli/core/network/Server.kt
Previous code only looked for translation support on Mastodon servers. It may be present on Hometown/Glitch servers too, so check.
Fixes #714
=> feat: Check Hometown/Glitch server instanceinfo for translation support

app/lint-baseline.xml, app/src/main/java/app/pachli/EditProfileActivity.kt, app/src/main/java/app/pachli/components/compose/ComposeActivity.kt, app/src/main/java/app/pachli/components/compose/MediaUploader.kt, app/src/main/java/app/pachli/components/notifications/NotificationsFragment.kt, app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt, app/src/main/java/app/pachli/components/viewthread/ViewThreadFragment.kt, app/src/main/java/app/pachli/fragment/SFragment.kt, app/src/main/java/app/pachli/usecase/TimelineCases.kt, app/src/main/java/app/pachli/viewmodel/EditProfileViewModel.kt, app/src/test/java/app/pachli/usecase/TimelineCasesTest.kt, core/ui/src/main/kotlin/app/pachli/core/ui/extensions/ThrowableExtensions.kt, feature/login/build.gradle.kts, feature/login/src/main/kotlin/app/pachli/feature/login/LoginActivity.kt
Previous code was inconsistent about using getServerErrorMessage() and whether or not the case where getServerErrorMessage() returns null was handled.
Switch to using getErrorString() which does handle the null case and always returns a usable string.
Some string resources are rendered temporarily unused by this change. They will be used again soon, so configure lint to ignore them at the moment.
=> fix: Generate useful error messages for all errors

feature/lists/src/main/kotlin/app/pachli/feature/lists/ListsActivity.kt
Previous code didn't hide the list-of-lists if an error occurred after the list was displayed (e.g., load the list, turn on airplane mode, reload the list).
Hide the list when errors are shown, and show it when there is content.
=> fix: Show/hide the list of lists appropriately when showing errors

core/common/src/main/kotlin/app/pachli/core/common/PachliError.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/ServerRepository.kt, core/network/src/main/kotlin/app/pachli/core/network/retrofit/apiresult/ApiResult.kt
Simplifies the case where there are no format args.
=> refactor: Allow PachliError.formatArgs to be null

app/lint-baseline.xml, app/src/main/java/app/pachli/TabPreferenceActivity.kt, app/src/main/java/app/pachli/components/compose/ComposeAutoCompleteAdapter.kt, app/src/main/java/app/pachli/components/compose/view/ComposeScheduleView.kt, app/src/main/java/app/pachli/components/drafts/DraftHelper.kt, app/src/main/java/app/pachli/components/notifications/NotificationFetcher.kt, app/src/main/java/app/pachli/components/search/adapter/SearchHashtagsAdapter.kt, app/src/main/java/app/pachli/network/FilterModel.kt, app/src/main/java/app/pachli/util/StatusViewHelper.kt, app/src/main/res/values/strings.xml, core/common/lint-baseline.xml, core/common/src/main/kotlin/app/pachli/core/common/util/NumberUtils.kt, feature/login/lint-baseline.xml, gradle/libs.versions.toml
New lint checks mean:
- Some trivial uses of String.format() are replaced with templates
- Use a string resource for the scheduled date and time
Some reported SetTextI18n warnings have been ignored, as they relate to e.g., clearing a view's text by setting it to "".
=> chore(deps): update agp to v8.5.0, lint to 31.5.0

app/lint-baseline.xml, app/src/main/AndroidManifest.xml, app/src/main/java/app/pachli/PachliApplication.kt, app/src/main/java/app/pachli/di/InitializerEntryPoint.kt, app/src/main/java/app/pachli/initializer/DependencyGraphInitializer.kt, app/src/main/java/app/pachli/initializer/TimberInitializer.kt, app/src/main/java/app/pachli/initializer/WorkManagerInitializer.kt, gradle/libs.versions.toml
Move initialisation of WorkManager and Timber in to new `Initializer` classes, managed by `androidx.startup`.
There's a false-positive `BadConfigurationProvider` lint message because the `Configuration.Provider` is in the content provider and not the application class.
=> refactor: Use androidx.startup for startup activities

app/src/main/res/layout/activity_view_thread.xml
Previous layout set `navigationContentDescription` to `action_open_drawer`, which is not correct for that part of the UI.
Remove it, and the default "Navigate up" is used.
=> fix: Use default "Navigate up" content description in ViewThreadActivity

core/common/src/main/kotlin/app/pachli/core/common/util/BlurHashDecoder.kt
By Christophe Beyls in https://github.com/tuskyapp/Tusky/pull/4515. Their commit notes:
Improve the performance of `BlurHashDecoder` while also reducing memory allocations.
- Precompute cosines tables before composing the image so each cosine value is only computed once.
- Compute cosines tables once if both are identical (for square images with the same number of colors in both dimensions).
- Store colors in a one-dimension array instead of a two-dimension array to reduce memory allocations.
- Use a simple String.indexOf() to find the index of a Base83 char, which is both faster and needs less memory than a HashMap thanks to better locality and no boxing of chars.
- No cache is used, so computations may be performed in parallel on background threads without the need for synchronization …
=> refactor: Improve blurhash decoding performance

app/lint-baseline.xml, app/src/main/java/app/pachli/MainActivity.kt, app/src/main/java/app/pachli/util/ShareShortcutHelper.kt, core/designsystem/lint-baseline.xml
Previous code created one shortcut per account, which could exceed the maximum number of shortcuts allowed, causing a crash.
Fix this by creating no more than the max number of shortcuts while ensuring that the active account is always included.
Fixes #752
=> fix: Don't exceed the maximum number of created shortcuts

app/src/main/java/app/pachli/MainActivity.kt, app/src/main/res/layout/material_drawer_header.xml, core/designsystem/src/main/res/values-night/theme_colors.xml, core/designsystem/src/main/res/values/colors.xml
The user might have set a profile header image that is close to the colour of the text in the account header in the left navigation menu. This can make the text difficult or impossible to see.
Work around this by drawing a partially transparent scrim behind the text so it's always displayed over a background that makes the text legible.
Fixes #298
=> fix: Ensure text in nav menu account header is legible

app/src/main/java/app/pachli/adapter/StatusBaseViewHolder.kt, app/src/main/res/layout/item_media_preview.xml, core/ui/src/main/kotlin/app/pachli/core/ui/TextViewWithVerticallyAlignedDrawable.kt
Previous code did not provide whitespace between different media labels when media is not loaded.
In addition, the icon for the media was centre-aligned vertically with the text, making it difficult to scan and determine when one media label ends and another one starts.
Fix this by adding an 8dp margin between the media labels, and using a TextView subclass that vertically aligns the media icon with the first line of text.
Set the compound drawables with relative alignment, so they behave appropriately in RTL layouts.
Fixes #751.
=> fix: Improve readability of status media labels

app/src/main/java/app/pachli/components/preference/PreferencesActivity.kt
Implementing predictive back support inadvertently broke the code ensuring activities are restarted when the font size or family changes. So the user could change the font in Preferences, see the change be immediately reflected in the preferences screen, then go back to the previous activity and the change wouldn't be reflected.
Fix this by restoring some of the previous code.
=> fix: Set font size and family when going back from Preferences

.editorconfig
ktlint 1.3.0 promoted some experimental rules to the standard set, and they some significant code churn if applied:
- Rewriting class signatures
- Rewriting conditions
- Rewriting single statement functions
Disable them for the time being.
=> chore: Disable new ktlint formatting rules

gradle/libs.versions.toml
3.3.0 has a race condition when `getItem` is called.
The fix is in https://android-review.googlesource.com/c/platform/frameworks/support/+/3156343
but not released yet.
See:
- https://issuetracker.google.com/issues/343124454
- https://issuetracker.google.com/issues/349090863
=> revert: Downgrade androidx-paging to version 3.2.1

app/src/main/java/app/pachli/adapter/StatusBaseViewHolder.kt, app/src/main/java/app/pachli/components/trending/TrendingLinkViewHolder.kt, app/src/main/java/app/pachli/components/trending/TrendingLinksAccessibilityDelegate.kt, app/src/main/java/app/pachli/components/trending/TrendingLinksAdapter.kt, app/src/main/java/app/pachli/components/trending/TrendingLinksFragment.kt, app/src/main/java/app/pachli/util/ListStatusAccessibilityDelegate.kt, app/src/main/java/app/pachli/view/PreviewCardView.kt, app/src/main/res/layout/preview_card.xml, app/src/main/res/values/strings.xml, core/designsystem/src/main/res/values/dimens.xml, core/network/src/main/kotlin/app/pachli/core/network/model/Card.kt, core/network/src/main/kotlin/app/pachli/core/network/model/TrendsLink.kt, core/preferences/src/main/kotlin/app/pachli/core/preferences/CardViewMode.kt, core/ui/src/main/res/values/actions.xml
Mastodon now supports additional (optional) author information to show as a byline on preview cards.
Use this (if included), to show the author's avatar, name, and link to their profile. If tapped a click on a new `Target.BYLINE` target is registered allowing fragments/activities to launch `ViewProfileActivity`.
Include this as an action in `ListStatusAccessibilityDelegate`, and provide `TrendingLinksAccessibilityDelegate` to provide accessibility actions when viewing trending links.
=> feat: Show author bylines on preview cards, tap to view profile

app/build.gradle.kts, app/lint-baseline.xml, app/src/main/java/app/pachli/adapter/StatusBaseViewHolder.kt, app/src/main/java/app/pachli/adapter/StatusDetailedViewHolder.kt, app/src/main/java/app/pachli/util/StatusExtensions.kt, app/src/main/res/values/donottranslate.xml, core/network/src/main/kotlin/app/pachli/core/network/model/TimelineAccount.kt
Previous code blindly inserted commas and semi-colons as separators between the components of a content description. If some of those components were null you could have a content description that looked like "... , , , ..." or similar, and the repeated reading of "comma" by screen readers was jarring and reduced accessibility.
Fix this by inserting punctuation only where necessary, building up the string piece by piece instead of using a string resource with hardcoded punctuation.
Fixes #791.
=> fix: Correctly punctuate a status content description

app/src/main/java/app/pachli/components/compose/ComposeActivity.kt
Previous code set `doOnTextChanged` listener for the content warning *after* the initial value had been set. This meant the initial content warning text was not included when calculating the status' initial length.
Fix that by setting the listener before the text is set.
Fixes #815
=> fix: Ensure initial status length calculation includes the content warning

app/src/main/java/app/pachli/MainActivity.kt
`getOrElse { null }` is synonymous with `get()` when using kotlin-result.
=> refactor: Replace `getOrElse { null }` with get()

app/src/main/java/app/pachli/adapter/StatusDetailedViewHolder.kt, app/src/main/java/app/pachli/viewdata/StatusViewData.kt
Holdover from when Java interoperability was required.
=> change: Remove copyWithCollapsed helper

app/src/main/java/app/pachli/components/search/SearchActivity.kt
Previous code always focused the search query. This meant that if the user:
1. Searched for something
2. Opened a result (post, hashtag, account)
3. Navigated back to the search results
then because the query was focused the soft-keyboard would open, obscuring the list of results. The user had to press "Back" again to dismiss the keyboard.
New code only focuses the search query view if it is empty. This allows the user to come back to the list of results and immediately open a new result.
=> fix: Don't focus search query when returning to the results list

core/designsystem/src/main/res/values/styles.xml
RadioButton and CheckBox color the selected radio button or check box using `colorPrimary`. For some reason Material dialogs don't, and use `colorSecondary` for this (and only this), which leads to visual inconstencices through the app.
Fix this by setting `colorSecondary` to `colorPrimary` to force it.
=> fix: Use colorPrimary for checked/selected dialog items

core/network/src/main/kotlin/app/pachli/core/network/Server.kt, core/network/src/test/kotlin/app/pachli/core/network/ServerTest.kt
Previous code had the version test in the wrong order, so the check for >= 0.15.0 took precedence.
=> fix: Enable server filtering on GoToSocial 0.16+

app/src/main/java/app/pachli/view/FontFamilyDialogFragment.kt
Ensures it is not possible to forget to recycle the attribute array.
=> refactor: Use withStyledAttributes in FontFamilyDialogFragment

core/network/src/main/kotlin/app/pachli/core/network/Server.kt
The Glitch fork reports the same version number as stock Mastodon and is supposed to have the same baseline capabilities as stock Mastodon at that version number.
=> fix: Support same capabilities on Glitch as Mastodon

app/src/main/res/layout/item_trending_cell.xml
Previously re-binding the tag's text wouldn't re-measure the layout when the text changed. So scrolling down a longer tag could be placed in a textview that previously held a shorter tag.
Then it was cut off and the user couldn't see what the tag was. Use `wrap_content` so size is measured when the content changes.
=> fix: Ensure trending tag name is fully visible

app/src/main/java/app/pachli/components/search/SearchActivity.kt, app/src/main/java/app/pachli/components/search/SearchOperator.kt, app/src/main/java/app/pachli/components/search/SearchOperatorViewData.kt, app/src/main/res/layout/search_operator_date_dialog.xml, app/src/main/res/values/strings.xml
When selecting a search date range show the user a dialog with some pre-set options, and a button that allows them to pick a custom date range.
=> feat: Include pre-set date search options

app/src/main/java/app/pachli/TimelineActivity.kt, app/src/main/java/app/pachli/components/preference/AccountPreferencesFragment.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/FiltersRepository.kt
The `canFilter()` implementation could crash if `server` (marked `lateinit`) hadn't been initialised at the point of use.
Fix this by removing it and adjusting the two callers to use the `filters` flow and take appropriate action on error.
=> fix: Don't crash due to Filters/ServerRepository race condition

app/src/main/res/layout/item_status.xml
Previous code set a min-height, which is no longer necessary after the other layout changes. But it meant that a preview card with a one-line title, no synopsis, and a URL, was taking up too much vertical space.
=> fix: Reduce preview cards to minimum height required

app/src/main/java/app/pachli/view/PreviewCardView.kt, app/src/main/res/layout/preview_card.xml
Byline changes inadvertently changed how the preview image is laid out, breaking the "Image at start, info at end" variant.
Previous code did not always show the card description if the text was present, fix that.
=> fix: Correctly position preview card images, show card description

app/lint-baseline.xml, app/src/main/java/app/pachli/components/preference/LabPreferencesFragment.kt, app/src/main/java/app/pachli/components/preference/PreferencesFragment.kt, app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt, app/src/main/res/layout/fragment_lab_preferences_warning.xml, app/src/main/res/values/strings.xml, app/src/test/java/app/pachli/components/timeline/CachedTimelineViewModelTestUiState.kt, app/src/test/java/app/pachli/components/timeline/NetworkTimelineViewModelTestUiState.kt, core/preferences/src/main/kotlin/app/pachli/core/preferences/SettingsConstants.kt
Add a new set of preferences, "Lab experiments", to control features that are under investigation and may never make it into the mainstream.
Add the first experimental feature, which reverses the order of the home timeline, so posts are shown oldest first instead of newest first.
=> feat: Experimental preference to reverse home timeline

app/lint-baseline.xml, app/src/main/java/app/pachli/components/search/SearchActivity.kt, app/src/main/res/drawable/ic_link_24.xml, app/src/main/res/layout/activity_search.xml, core/designsystem/src/main/res/values/styles.xml
Two problems with the previous code when search filters were visible:
1. The link icon overrode the tint, so didn't appear correctly in dark and black mode.
2. The horizontal scroll view had the wrong background colour in black mode.
Fix both, by updating the icon and adding a new style for the scroll view.
While I'm here remove an obsolete comment and tighten up visibility.
Fixes #875
=> fix: Search filters use correct colours in dark and black mode

feature/login/src/main/res/values-bg/strings.xml, feature/login/src/main/res/values-bn-rBD/strings.xml, feature/login/src/main/res/values/strings.xml
The help text used to mention that an account could be created at the user's server. This was not done in Pachli, but could confuse reviewers into thinking it was.
Drop the reference to prevent this confusion.
=> change: Drop any mention of account creation

app/src/main/res/layout/item_conversation.xml, app/src/main/res/layout/item_status.xml, app/src/main/res/layout/item_status_detailed.xml, core/ui/src/main/kotlin/app/pachli/core/ui/LinkHelper.kt
Previous code didn't set the textDirection for the status content, so the first para of RTL text might be rendered incorrectly.
In addition, mentions and tags weren't BIDI wrapped, so would appear as "foo@" and "foo#" in RTL statuses, instead of "@foo" and "#foo".
Fix both of these issues.
Fixes #870
=> fix: Render hashtags, mentions, and initial paras correctly in RTL

.github/workflows/upload-orange-release-google-play.yml
This should work again after the most recent release was approved.
Reverts pachli/pachli-android#895
=> ci: Automatically send changes for review

app/src/main/res/layout/item_conversation.xml, app/src/main/res/layout/item_status.xml, app/src/main/res/layout/item_status_detailed.xml
It's overly eager to switch, and renders incorrectly with content like:
> I like the letter י because it's so small
=> fix: Remove anyRTL from status root view

app/src/main/java/app/pachli/adapter/StatusDetailedViewHolder.kt
Previous code had a bug/typo, which meant the app the user was posting from was not shown if the app did not have an associated website. But the bullet separating the parts of the text was still shown, resulting in a spurious dangling bullet.
=> fix: Show posting app name if app link is missing

app/src/main/java/app/pachli/components/compose/MediaUploader.kt
Previous code used `filterIsInstance<Ok<UploadEvent.FinishedEvent>>()`.
This can fail at runtime with class cast exception because the type in `Ok<...>` is erased so `filterIsInstance` was accepting any `Ok` `Result`. Later attempts to operate on it as a `.FinishedEvent` generated the run time error.
Fix that by explicitly checking the type of the `Ok` result in `first` instead.
=> fix: Prevent crash when sending a post while media is uploading

app/src/main/res/layout/fragment_view_video.xml
androidx.media3 1.4.0-rc01 and above (at the time of writing) has a bug that breaks shared element transitions with a `PlayerView` (see https://github.com/androidx/media/issues/1594).
This can be worked around by setting `app:surface_type="texture_view"`. This uses more power, but for the typical length of social media videos this shouldn't be a problem at the moment.
Fixes #920.
=> fix: Restore video transitions on androidx.media3 1.4.0 and 1.4.1

app/src/main/java/app/pachli/view/PreviewCardView.kt, app/src/main/res/layout/preview_card.xml
In rare occasions the preview card text could overlap the image if the image had a portrait aspect ratio.
This seems to be due to the use of the `with(...) {}` scope function and Kotlin's interoperability with Java setters.
Replace this with code that explicitly gets and sets the layout params to ensure they are set correctly.
=> fix: Stop preview card text overlapping images

app/src/main/java/app/pachli/components/accountlist/AccountListFragment.kt, core/network/src/main/kotlin/app/pachli/core/network/retrofit/MastodonApi.kt
Previous code used `Response`. Convert to `ApiResult` as part of the work to implement anti-harassment controls, which will need to query the user's list of accounts they are following.
Converting just `accountFollowing` wasn't practical, as all the methods are called by a single function in `AccountListFragment` which expects the return type to be the same.
=> refactor: Use ApiResult for requests that return lists of accounts

app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt
Previous code saved the reading position of a fully visible status. But there are situations where no status is fully visible.
1. The user is in the middle of viewing a status longer than the screen height, and the top/bottom of the status are off the top/bottom of the screen.
2. The user has scrolled between two statuses. Collectively they are longer than the screen height, and the top of one status is off the top of the screen and the bottom of the other status is off the bottom of the screen.
In both cases the user's reading position was not saved.
In these situations use the ID of the status closest to the bottom of the screen, even if not fully visible. This should ensure the user never missing anything.
Fixes #936
=> fix: Save the reading position if no post is fully visible

app/src/main/java/app/pachli/components/notifications/NotificationFetcher.kt, core/network/src/main/kotlin/app/pachli/core/network/retrofit/MastodonApi.kt
Previous code showed any JSON-wrapped errors from notification fetches
as the JSON string, instead of the error message.
Fix this by switching to `ApiResult` and using the formatted error
message.
Fixes 937
=> fix: Show notification fetch errors instead of JSON

core/common/src/main/kotlin/app/pachli/core/common/extensions/EnumExtensions.kt, core/network/src/main/kotlin/app/pachli/core/network/model/Status.kt
Use `enumEntries` instead of `enumValues`, which is now recommended.
Replace a `.getOrNull(...) ?: other` with `.getOrElse(...) { other }`.
=> refactor: Slightly improve enum extensions and usage

app/src/main/java/app/pachli/ViewMediaActivity.kt, app/src/main/java/app/pachli/adapter/StatusBaseViewHolder.kt, app/src/main/java/app/pachli/components/account/AccountActivity.kt, app/src/main/java/app/pachli/components/account/media/AccountMediaFragment.kt, app/src/main/java/app/pachli/components/conversation/ConversationsFragment.kt, app/src/main/java/app/pachli/components/notifications/NotificationsFragment.kt, app/src/main/java/app/pachli/components/report/fragments/ReportStatusesFragment.kt, app/src/main/java/app/pachli/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt, app/src/main/java/app/pachli/components/viewthread/ViewThreadFragment.kt, app/src/main/java/app/pachli/fragment/SFragment.kt, core/domain/src/main/kotlin/app/pachli/core/domain/DownloadUrlUseCase.kt, core/navigation/src/main/kotlin/app/pachli/core/navigation/AttachmentViewData.kt, core/navigation/src/main/kotlin/app/pachli/core/navigation/Navigation.kt, core/preferences/src/main/kotlin/app/pachli/core/preferences/DownloadLocation.kt, core/preferences/src/main/res/values/strings.xml
Update `DownloadUrlUseCase` with a parameter to specify the account that "owns" the media. This is either the account that posted the status, or the account being viewed (e.g., if downloading an account's header image).
Add a new `DownloadLocation` enum constant to download to directories named after that account.
Pass this information through at the call sites.
Fixes #938
=> feat: Add option to download media to per-sender directories

app/src/main/java/app/pachli/components/notifications/NotificationsFragment.kt, app/src/main/java/app/pachli/components/notifications/NotificationsViewModel.kt, app/src/main/java/app/pachli/components/preference/PreferencesFragment.kt, app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt, app/src/test/java/app/pachli/components/notifications/NotificationsViewModelTestUiState.kt, core/preferences/src/main/kotlin/app/pachli/core/preferences/SettingsConstants.kt, core/preferences/src/main/kotlin/app/pachli/core/preferences/SharedPreferencesRepository.kt, core/preferences/src/main/kotlin/app/pachli/core/preferences/TabTapBehaviour.kt, core/preferences/src/main/res/values/strings.xml
Previously, tapping a tab would jump to the top of the loaded content, which might trigger a load of a fresh page.
Provide a preference to control this; the default is the current behaviour, the user can also choose to discard the current content and load the newest content.
Fixes #939
=> feat: Allow the user to chose behaviour when tapping a tab

app/src/main/java/app/pachli/components/conversation/ConversationViewHolder.kt, app/src/main/res/values/strings.xml
It's possible for some servers to return a conversation that has an empty (or possibly missing) `accounts` property. In the previous code this would crash trying to access an item in an empty list.
Fix this by handling the "no participants" case.
Fixes #971
=> fix: Don't crash if a conversation has no participants

core/network/src/main/kotlin/app/pachli/core/network/model/Announcement.kt
The `Status` type associated with an announcement is entirely different to the regular `Status` type, with a different JSON shape. The incorrect type meant a deserialisation error when loading announcements with associated statuses.
=> fix: Load announcements with associated statuses correctly

app/src/main/java/app/pachli/components/scheduled/ScheduledStatusActivity.kt, core/network/src/main/kotlin/app/pachli/core/network/model/StatusParams.kt
Previous code didn't deserialise the "poll" attribute so it was never passed to the composer when editing scheduled statuses.
Fixes #991
=> fix: Parse and restore poll when editing scheduled statuses

core/database/src/main/kotlin/app/pachli/core/database/model/TimelineStatusEntity.kt
ForeignKey constraints can be invalidated in the middle of a transaction even if a later statement in the same transaction will make them valid again. This seems to be causing production crashes.
Defer foreign key constraint checks until the end of the transaction to prevent this.
=> fix: Don't crash if foreign key constraint is invalid in transaction

app/src/main/java/app/pachli/components/compose/ComposeActivity.kt, app/src/main/java/app/pachli/components/compose/ComposeViewModel.kt, app/src/main/java/app/pachli/components/preference/PreferencesFragment.kt, app/src/main/res/values/strings.xml, core/preferences/src/main/kotlin/app/pachli/core/preferences/SettingsConstants.kt, core/preferences/src/main/kotlin/app/pachli/core/preferences/SharedPreferencesRepository.kt
For some users this feature has too many false positives, particularly when emojis are used.
Provide a preference that enables/disables the feature, default to "enable".
When the user is prompted the dialog has a third "Don't ask again" option. If chosen the preference is set to prevent future prompts and the status is sent as-is.
Fixes #893
=> feat: Add "Don't ask again" option when confirming the posting language

feature/suggestions/src/main/res/layout/item_suggestion.xml
Previous layout didn't constraint the metadata elements to the parent's edge, so could run off the screen if the content was too long.
Constrain them so the content wraps correctly.
Fixes #876
=> fix: Ensure suggested account information is not cut off

core/data/src/main/kotlin/app/pachli/core/data/repository/NetworkSuggestionsRepository.kt
The "Suggested accounts" API returns dormant accounts. See this bug report: https://github.com/mastodon/mastodon/issues/30674.
That's bad UX, so filter out any account that hasn't posted in the last 28 days.
Fixes #1029
=> feat: Ignore suggested accounts that haven't posted in 28 days

app/src/main/java/app/pachli/components/compose/ComposeActivity.kt, app/src/main/java/app/pachli/components/compose/ComposeViewModel.kt, app/src/main/java/app/pachli/components/compose/view/ComposeScheduleView.kt, app/src/main/java/app/pachli/components/drafts/DraftHelper.kt, app/src/main/java/app/pachli/service/SendStatusService.kt, core/database/schemas/app.pachli.core.database.AppDatabase/7.json, core/database/schemas/app.pachli.core.database.AppDatabase/8.json, core/database/src/main/kotlin/app/pachli/core/database/AppDatabase.kt, core/database/src/main/kotlin/app/pachli/core/database/model/DraftEntity.kt, core/navigation/src/main/kotlin/app/pachli/core/navigation/Navigation.kt, core/network/src/main/kotlin/app/pachli/core/network/model/NewStatus.kt, core/network/src/main/kotlin/app/pachli/core/network/model/ScheduledStatus.kt
Previous code accepted the `scheduledAt` value as a String, and kept it as a String (including when serialising as part of a draft). Then it was converted to an actual Date for display.
Refactor to keep it as a Date for as long as possible. Moshi decodes Dates correctly over the network, and the database is configured to serialise Dates as Longs.
This necessitates two migration steps to preserve any existing `scheduledAt` values for drafts. The first step adds a new column to store the date as a Long and copies over existing data. The second step replaces the old column with the new column.
=> refactor: Use Date type for scheduled post date / times

app/src/main/java/app/pachli/components/scheduled/ScheduledStatusAdapter.kt, app/src/main/res/layout/item_scheduled_status.xml
=> feat: Show each post's scheduled time in the list of scheduled posts

app/src/main/java/app/pachli/components/scheduled/ScheduledStatusActivity.kt, core/network/src/main/kotlin/app/pachli/core/network/model/StatusParams.kt
Previous code didn't send the language to ComposeActivity when editing a scheduled status so it always appeared to be dirty. This prompted the user to save/discard changes when backing out, even if they hadn't made any changes.
Fix this by collecting the language code when fetching scheduled posts and passing it in `ComposeOptions`.
=> fix: Don't prompt to discard/save unedited scheduled posts

app/src/main/java/app/pachli/MainActivity.kt, app/src/main/java/app/pachli/components/preference/LabPreferencesFragment.kt, app/src/main/java/app/pachli/components/preference/PreferencesActivity.kt, app/src/main/res/layout/activity_main.xml, core/preferences/src/main/kotlin/app/pachli/core/preferences/SettingsConstants.kt, core/preferences/src/main/kotlin/app/pachli/core/preferences/SharedPreferencesRepository.kt, core/preferences/src/main/kotlin/app/pachli/core/preferences/TabAlignment.kt, core/preferences/src/main/kotlin/app/pachli/core/preferences/TabContents.kt, core/preferences/src/main/res/values/strings.xml, core/ui/src/main/kotlin/app/pachli/core/ui/AlignableTabLayout.kt
Provide two new lab preferences for controlling the layout and content of main navigation tabs.
Tabs can now be justfied to start, end, or fully (if room). Start/end justification may put the tabs closer to the user's fingers, depending on how they hold the device. Fully justified uses the full width of the tab bar (if the tabs don't require scrolling).
The content can be set to one of:
- Icon only (previous behaviour)
- Text only
- Icon with text beside
- Icon with text below
Fixes #336
=> feat: Add accessibility options for tab justification and content

feature/lists/src/main/kotlin/app/pachli/feature/lists/AccountsInListFragment.kt, feature/lists/src/main/kotlin/app/pachli/feature/lists/ListsForAccountFragment.kt, feature/lists/src/main/res/layout/item_account_in_list.xml, feature/lists/src/main/res/layout/item_add_or_remove_from_list.xml
User reports suggested that the "x" / "+" icons used to add / remove accounts from lists could be difficult to visually distinguish.
Replace with checkboxes. Checked indicates the account is in the list, unchecked indicates it isn't. Clicking the checkbox to change state changes the presence in the list.
Fixes #812
=> change: Use checkboxes to show whether an account is a member of a list

app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt
Previous code only inflated the timeline fragment menu if swipe/refresh was enabled -- a hold over from when "Refresh" was the only menu item.
There are other menu items now, and they were also hidden. Fix this by always inflating the menu.
=> fix: Always create per-timeline menu

app/src/main/java/app/pachli/util/ListStatusAccessibilityDelegate.kt
Previous code checked the item was a `StatusViewData`, which is not true for notifications, and meant the links, mentions, and hashtags accessibility features were not available.
Change this to `IStatusViewData`, which notifications do implement.
Fixes #1037
=> fix: Show links, mentions, and hashtag accessibility actions for notifications

app/src/main/java/app/pachli/util/ListStatusAccessibilityDelegate.kt, app/src/main/res/layout/simple_list_item_1_copy_button.xml, app/src/main/res/values/strings.xml, core/network/src/main/kotlin/app/pachli/core/network/model/Status.kt
Users report that copying items can be difficult using Talkback.
Make this easier in the dialogs that appear for links, mentions, and hashtags by using a dedicated adapter that displays a "Copy" button at the end of each item.
Fixes #1038
=> feat: Show "copy" button for links/hashtags/mentions in accessibility dialogs

app/src/main/java/app/pachli/util/ListStatusAccessibilityDelegate.kt
Previous code passed the actionable status, so "Open boost author" actually opened the account that posted the original status.
Pass the status representing the boost, so the correct account is opened.
Fixes #1042
=> fix: Make "Open boost author" open the correct profile

app/src/main/java/app/pachli/components/compose/dialog/CaptionDialog.kt, app/src/main/res/layout/dialog_image_description.xml
Previous layout didn't enable the character counter for entered text, so it was difficult for the user to see how much they had used.
Fix that. To get the layout to play nicely switch to a ConstraintLayout with a chain to split the dialog roughly 50/50 between the image and the caption views.
While I'm here:
- Remove the margins around the image, so it's clearer, and is more consistent with the "set focus" dialog.
- Set focus on the description immediately, so the keyboard pops up.
- Remove focusability from the image, since the user shouldn't be able to interact with it.
=> feat: Show text counter on caption dialog, request focus

core/ui/src/main/kotlin/app/pachli/core/ui/ClickableSpanTextView.kt, core/ui/src/main/kotlin/app/pachli/core/ui/LinkHelper.kt
This makes it easier to share links from a regular timeline (where text is not selectable).
Listen for long clicks on spans by launching a delayed runnable that waits `getLongPressTimeout()` ms before sending an intent that shows the share sheet for the clicked span.
If the span's link is not the same as the text (e.g., it's a mention or a hashtag) then the text of the span is also sent as the title to show in the share sheet.
While I'm here, the official LinkMovementMethodCompat does the same job as NoTrailingSpaceLinkMovementMethod, so delete the latter code in favour of the former.
Fixes #695
=> feat: Show share sheet when long clicking links/hashtags/mentions

app/src/main/res/layout/dialog_image_description.xml
Constrain caption image height so the caption field is always visible. Allow for at least 4 lines of space to enter the caption.
=> fix: Ensure caption field is always visible

app/src/main/AndroidManifest.xml
Some users report that returning to the `ComposeActivity` loses content they've entered and returns to `MainActivity`. I can't reproduce this, but it's possible that Android is clearing the task state and returning to the root activity (`MainActivity` in this case).
Set `alwaysRetainTaskState` to true to keep the activity stack, and hopefully prevent this from happening.
=> fix: Retain task state for MainActivity and ComposeActivity

app/src/main/java/app/pachli/components/notifications/SeveredRelationshipsViewHolder.kt, app/src/main/res/layout/item_severed_relationships.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-gl/strings.xml, app/src/main/res/values-nb-rNO/strings.xml, app/src/main/res/values/strings.xml, core/network/src/main/kotlin/app/pachli/core/network/model/Notification.kt, core/network/src/main/kotlin/app/pachli/core/network/model/RelationshipSeveranceEvent.kt
Previous code was missing the JSON name of the event, so it wasn't present when it should have been, resulting in a crash.
Also, the Mastodon documentation is incorrect about the relationship count, which is instead represented as two properties, one for followers and one for following. So model that, and display them separately in the UI.
Fixes #1086
=> fix: Don't crash on relationship severance events

app/src/test/java/app/pachli/components/viewthread/ViewThreadViewModelTest.kt
Some tests were assuming the uiState would transition from .Loading to .Success, without considering there might be a .LoadingThread intermediate step. Cater for that to prevent test flakes.
=> test: Fix ViewThreadViewModel flakiness

core/database/src/main/kotlin/app/pachli/core/database/AppDatabase.kt, core/database/src/main/kotlin/app/pachli/core/database/di/DatabaseModule.kt
Previous migration code could crash if the `clientId` or `clientSecret` columns were null during the migration (unclear how that could happen but there's at least one user report of this crash).
Re-write the migration to set these columns to the empty string if NULL first.
=> fix: Ensure clientId and clientSecret are non null during db migration

app/src/main/java/app/pachli/adapter/FilterableStatusViewHolder.kt, app/src/main/java/app/pachli/adapter/StatusViewHolder.kt, app/src/main/java/app/pachli/components/notifications/NotificationsFragment.kt, app/src/main/java/app/pachli/components/notifications/NotificationsPagingAdapter.kt, app/src/main/java/app/pachli/components/notifications/NotificationsViewModel.kt, app/src/main/java/app/pachli/components/timeline/TimelinePagingAdapter.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt, app/src/main/java/app/pachli/components/viewthread/ThreadAdapter.kt, app/src/main/java/app/pachli/components/viewthread/ViewThreadViewModel.kt, app/src/main/java/app/pachli/viewdata/NotificationViewData.kt, app/src/main/java/app/pachli/viewdata/StatusViewData.kt
`IStatusViewData.filterAction` was the `FilterAction` to apply to the status based on the status' content.
As new filter options will apply filters based on the account that sent the status, rename to `contentFilterAction` so it's easy to distinguish between the two.
=> refactor: rename `filterAction` property to `contentFilterAction`

app/src/main/java/app/pachli/ViewMediaActivity.kt, app/src/main/java/app/pachli/components/account/AccountActivity.kt, app/src/main/java/app/pachli/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/app/pachli/components/trending/TrendingLinksAccessibilityDelegate.kt, app/src/main/java/app/pachli/fragment/SFragment.kt, core/ui/src/main/kotlin/app/pachli/core/ui/ClipboardUseCase.kt, core/ui/src/main/kotlin/app/pachli/core/ui/accessibility/ArrayAdapterWithCopyButton.kt, core/ui/src/main/kotlin/app/pachli/core/ui/di/UseCaseEntryPoint.kt, feature/about/src/main/kotlin/app/pachli/feature/about/AboutFragment.kt
Previous code was inconsistent about whether or not a notification toast was shown after copying text (contrary to platform guidelines), and there was some code duplication.
Fix this with a new `ClipboardUseCase` with a `copyTextTo` method that handles copying text to the clipboard and showing a message afterwards (depending on platform level).
=> refactor: Ensure copying text experience is consistent

app/src/main/java/app/pachli/components/notifications/NotificationFetcher.kt, core/activity/src/main/kotlin/app/pachli/core/activity/BaseActivity.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/AccountManager.kt, core/database/src/main/kotlin/app/pachli/core/database/dao/AccountDao.kt
Chooser dialog could start before any accounts have loaded. Fix by collecting the account flow and waiting for the first emission (convert the flow to shared instead of state so there's no initial empty list).
Guard against the potential for a similar issue when fetching notifications.
Order the list of accounts with active account first so that code that skips it by ignoring the first item works correctly.
=> fix: Prevent crash when showing account chooser

app/src/main/java/app/pachli/MainActivity.kt, app/src/main/java/app/pachli/components/account/AccountActivity.kt, app/src/main/java/app/pachli/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/app/pachli/fragment/SFragment.kt, core/activity/src/main/kotlin/app/pachli/core/activity/AccountSelectionListener.kt
`AccountSelectionListener` only has one method; converting to a Kotlin `fun interface` simplifies the calling code.
=> refactor: Convert `AccountSelectionListener` to `fun interface`

app/src/test/java/app/pachli/StatusComparisonTest.kt, app/src/test/java/app/pachli/components/timeline/CachedTimelineRemoteMediatorTest.kt, app/src/test/java/app/pachli/components/timeline/StatusMocker.kt, core/data/src/main/kotlin/app/pachli/core/data/model/Server.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/AccountManager.kt, core/data/src/test/kotlin/app/pachli/core/data/model/ServerTest.kt, core/network-test/src/main/kotlin/app/pachli/core/network/di/test/FakeNetworkModule.kt, core/network/src/main/kotlin/app/pachli/core/network/di/NetworkModule.kt, core/network/src/main/kotlin/app/pachli/core/network/json/LenientRfc3339DateJsonAdapter.kt, gradle/libs.versions.toml
Pleroma (and possibly other servers) can return dates that have no timezone. Previous code would fail to deserialise JSON in this state and show an error.
Patch around this by assuming anything with a missing timezone is in UTC (timezone suffix "Z").
Fixes #562
=> feat: Support Pleroma returning dates with no timezone

app/src/main/java/app/pachli/components/timeline/TimelinePagingAdapter.kt
getItemViewType is occasionally called with a position that's out of range; trying to get the item at that position throws an `IndexOutOfBoundsException`.
Catch it, and return the placeholder view type.
=> fix: Prevent crash with Paging IndexOutOfBoundsException

app/src/main/java/app/pachli/fragment/ViewVideoFragment.kt
Previous code showed the error message for the underlying cause, which might be too technical for the user. Prefer to use top level error message; hopefully that is more actionable.
Contributes to #1083
=> fix: Show top level error message when video playback fails

app/src/main/java/app/pachli/components/compose/ComposeActivity.kt
Previous code ran the setup routine whenever the account changed. I think this could result in the content being cleared when a notification arrived (processing the notification updates the marker, which updates the account, which triggers a new collection).
Fix this by only taking the first emission of the account from the flow to do the setup.
=> fix: Don't clear content when account changes

app/src/main/java/app/pachli/appstore/CacheUpdater.kt, app/src/main/java/app/pachli/components/timeline/CachedTimelineRepository.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/CachedTimelineRemoteMediator.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/CachedTimelineViewModel.kt, app/src/main/java/app/pachli/components/viewthread/ViewThreadViewModel.kt, app/src/main/java/app/pachli/viewdata/StatusViewData.kt, app/src/test/java/app/pachli/components/timeline/CachedTimelineRemoteMediatorTest.kt, app/src/test/java/app/pachli/components/timeline/CachedTimelineViewModelTestBase.kt, app/src/test/java/app/pachli/components/timeline/StatusMocker.kt, app/src/test/java/app/pachli/components/viewthread/ViewThreadViewModelTest.kt, core/database/src/main/kotlin/app/pachli/core/database/Converters.kt, core/database/src/main/kotlin/app/pachli/core/database/dao/TimelineDao.kt, core/database/src/main/kotlin/app/pachli/core/database/model/TimelineStatusEntity.kt, core/database/src/test/kotlin/app/pachli/core/database/dao/TimelineDaoTest.kt
A few places in the code were calling `moshi.adapter` to marshall to/from strings in the database where type converters either already exist, or are straightforward to create.
Create the missing type converters, and use them throughout. This simplifies several places where a Moshi instance no longer needs to be passed through several layers of method calls.
Since this doesn't change the underlying database representation of the data there's no need to bump the database version number.
=> refactor: Use type converters instead calling moshi.adapter by hand

.github/workflows/ci.yml
Required on `main` according to https://github.com/github/codeql-action/issues/2117
=> ci: Add security-events write permission for SARIF upload

app/src/main/java/app/pachli/components/viewthread/edits/ViewEditsAdapter.kt, app/src/main/java/app/pachli/components/viewthread/edits/ViewEditsFragment.kt, app/src/main/java/app/pachli/components/viewthread/edits/ViewEditsViewModel.kt
Previous code only ran the status content through the diff engine, so changes to the content warning / spoiler text were ignored.
Fixes #1144
=> fix: Show content warning changes when viewing status edits

app/src/main/java/app/pachli/components/account/AccountViewModel.kt
Previous code would crash because toggling show boosts would treat this as a new follow, and try and insert a follower relationship in to the database where one already existed.
Fix this by providing explicit actions for show/hiding reblogs that don't disturb the follower relationship.
=> fix: Don't crash when toggling an account's "Show boosts" option

app/src/main/java/app/pachli/MainActivity.kt
Previous code could crash if the main drawer items weren't created before setting the optional items (scheduled statuses, lists, etc).
Protect the drawer item manipulation with a mutex to prevent this.
=> fix: Prevent race / crash when updating main drawer items

core/data/src/main/kotlin/app/pachli/core/data/repository/ServerRepository.kt
Previous code crashed because of a missing format argument.
=> fix: Include URL when constructing nodeinfo error string

plugins/markdown2resource/settings.gradle.kts, settings.gradle.kts
Without this an initial build on a machine with no JDK installed can fail with
```
A problem occurred configuring project ':feature:about'.
> Could not resolve all dependencies for configuration 'classpath'.
> Could not resolve project :markdown2resource.
Required by:
project :feature:about
> Failed to calculate the value of task ':markdown2resource:compileJava' property 'javaCompiler'.
> Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=17, vendor=any vendor, implementation=vendor-specific} for WINDOWS on x86_64.
> No locally installed toolchains match and toolchain download repositories have not been configured.
```
=> build: Add Java toolchain resolver

app/src/main/java/app/pachli/MainActivity.kt
Prevents a crash that would otherwise occur.
=> fix: Don't show "Remove tab" menu if there are no tabs

core/network/src/main/kotlin/app/pachli/core/network/retrofit/apiresult/ApiResult.kt, core/network/src/main/kotlin/app/pachli/core/network/retrofit/apiresult/ApiResultCall.kt, core/network/src/main/kotlin/app/pachli/core/network/retrofit/apiresult/SyncApiResultCallAdapter.kt, core/network/src/test/kotlin/app/pachli/core/network/retrofit/apiresult/ApiResultCallAdapterFactoryTest.kt, core/network/src/test/kotlin/app/pachli/core/network/retrofit/apiresult/ApiResultCallTest.kt, core/network/src/test/kotlin/app/pachli/core/network/retrofit/apiresult/TestCall.kt, core/testing/src/main/kotlin/app/pachli/core/testing/ApiResult.kt
Append the request method ("GET", etc) and the request URL to error messages in ApiResult errors. This should provide additional inforamtion when debugging issues reported by users.
=> feat: Show request method and URL in ApiResult errors

checks/build.gradle.kts
Prevents compilation errors complaining that the Java JVM version and Kotlin JVM version are different.
=> fix: Set the jvmToolChain version for the checks module

app/src/main/java/app/pachli/components/drafts/DraftHelper.kt, app/src/main/java/app/pachli/components/timeline/CachedTimelineRepository.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/CachedTimelineRemoteMediator.kt, app/src/main/java/app/pachli/usecase/LogoutUseCase.kt, app/src/test/java/app/pachli/components/timeline/CachedTimelineRemoteMediatorTest.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/AccountManager.kt, core/database/schemas/app.pachli.core.database.AppDatabase/11.json, core/database/src/main/kotlin/app/pachli/core/database/AppDatabase.kt, core/database/src/main/kotlin/app/pachli/core/database/dao/AccountDao.kt, core/database/src/main/kotlin/app/pachli/core/database/dao/AnnouncementsDao.kt, core/database/src/main/kotlin/app/pachli/core/database/dao/ConversationsDao.kt, core/database/src/main/kotlin/app/pachli/core/database/dao/FollowingAccountDao.kt, core/database/src/main/kotlin/app/pachli/core/database/dao/RemoteKeyDao.kt, core/database/src/main/kotlin/app/pachli/core/database/dao/TimelineDao.kt, core/database/src/main/kotlin/app/pachli/core/database/model/ConversationEntity.kt, core/database/src/main/kotlin/app/pachli/core/database/model/DraftEntity.kt, core/database/src/main/kotlin/app/pachli/core/database/model/FollowingAccountEntity.kt, core/database/src/main/kotlin/app/pachli/core/database/model/RemoteKeyEntity.kt, core/database/src/main/kotlin/app/pachli/core/database/model/TimelineStatusEntity.kt, core/database/src/test/kotlin/app/pachli/core/database/dao/AccountEntityForeignKeyTest.kt, core/database/src/test/kotlin/app/pachli/core/database/dao/TimelineDaoTest.kt
Previous code managed account deletions by having specific functions to call when an account was deleted that would delete all related data.
Replace this with proper foreign key references back to the account ID, and cascade account deletes to the related data.
Add tests to ensure the deletes happen as expected. Update existing tests to create an account where necessary so the new foreign key constraints are kept.
=> refactor: Delete account data using foreign key constraints

feature/about/build.gradle.kts
This improves the reproducibility of the build, as the "generated" field contains a timestamp which changes on every build.
=> build: Exclude "generated" field from aboutlibraries metadata

app/src/main/java/app/pachli/MainActivity.kt, app/src/main/java/app/pachli/TabPreferenceActivity.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/ListsRepository.kt, feature/lists/src/main/kotlin/app/pachli/feature/lists/ListsForAccountFragment.kt, feature/lists/src/main/kotlin/app/pachli/feature/lists/ListsForAccountViewModel.kt
Some parts of the UI already showed lists sorted by title, but not all.
The areas fixed are:
- The list of lists in the main drawer (left side navitation)
- The list of lists when adding/removing an account from a list
Fixes #1168
=> fix: Show lists sorted by title

core/database/src/main/kotlin/app/pachli/core/database/AppDatabase.kt, core/database/src/main/kotlin/app/pachli/core/database/di/DatabaseModule.kt
The default migration code copies existing NotificationEntity rows to the new table. This might fail because of the new FK constraint on TimelineAccountEntity. Fix this by not copying the data over; it's a local cache, so nothing of importance is lost.
=> fix: Prevent FK constraint failures in DB 12->13 migration

app/src/main/java/app/pachli/components/account/media/AccountMediaRemoteMediator.kt, app/src/main/java/app/pachli/components/conversation/ConversationsRemoteMediator.kt, app/src/main/java/app/pachli/components/conversation/ConversationsViewModel.kt, app/src/main/java/app/pachli/components/followedtags/FollowedTagsRemoteMediator.kt, app/src/main/java/app/pachli/components/instancemute/fragment/InstanceListFragment.kt, app/src/main/java/app/pachli/components/notifications/NotificationFetcher.kt, app/src/main/java/app/pachli/components/notifications/NotificationsViewModel.kt, app/src/main/java/app/pachli/components/report/adapter/StatusesPagingSource.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/CachedTimelineRemoteMediator.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/NetworkTimelineRemoteMediator.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt, app/src/main/java/app/pachli/components/viewthread/ViewThreadViewModel.kt, app/src/main/java/app/pachli/service/SendStatusService.kt, app/src/main/java/app/pachli/worker/PruneLogEntryEntityWorker.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/notifications/NotificationsRemoteMediator.kt
Previous code had legacy `try ... catch` blocks that could catch all exceptions, including `CancellationException`, thrown if the job of a suspending function is cancelled.
Indiscriminately catching those can interfere with cancellation, so use `currentCoroutineContext().ensureActive()` to rethrow the exception if the job has been cancelled.
=> fix: Ensure coroutine cancellations propograte, rethrow CancellationException

core/database/src/main/kotlin/app/pachli/core/database/dao/TimelineDao.kt, core/database/src/test/kotlin/app/pachli/core/database/dao/TimelineDaoTest.kt
Previous queries to delete stale data from the database could fail due to the new foreign key constraints.
Rewrite them so statuses and accounts referenced by cached notifications are not deleted.
=> fix: Rewrite prune cache worker queries to respect FK constraints

app/src/main/java/app/pachli/MainActivity.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/AccountManager.kt, core/data/src/main/res/values/strings.xml
Previous code would crash on an SQLiteException. Catch it and convert to a specific error.
=> fix: Show an error message if a Dao error occurs during login

.sqlfluff
Allows sqlfluff to format `LIMIT :limit` statements.
=> build: Add default limit placeholder value to sqlfluff config

app/src/main/java/app/pachli/appstore/CacheUpdater.kt, app/src/main/java/app/pachli/components/timeline/CachedTimelineRepository.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/CachedTimelineRemoteMediator.kt, app/src/test/java/app/pachli/components/timeline/CachedTimelineRemoteMediatorTest.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/notifications/NotificationsRemoteMediator.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/notifications/NotificationsRepository.kt, core/database/src/main/kotlin/app/pachli/core/database/AppDatabase.kt, core/database/src/main/kotlin/app/pachli/core/database/dao/StatusDao.kt, core/database/src/main/kotlin/app/pachli/core/database/dao/TimelineDao.kt, core/database/src/main/kotlin/app/pachli/core/database/di/DatabaseModule.kt, core/database/src/test/kotlin/app/pachli/core/database/dao/TimelineDaoTest.kt, core/testing/src/main/kotlin/app/pachli/core/testing/fakes/FakeDatabaseModule.kt
TimelineDao contained operations on timelines and statuses which made it large and confusing.
Factor out the status-specific operations in to the new StatusDao class to make things more understandable.
=> refactor: Create StatusDao for operations that act on individual statuses

app/src/main/java/app/pachli/components/timeline/viewmodel/CachedTimelineRemoteMediator.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/notifications/NotificationsRemoteMediator.kt
Previous code used a transaction for updates to the database, but didn't do the earlier reads in the same transaction. Theoretically this could race.
Guard against this by using a single transaction for a complete remote mediator operation (refresh, prepend, append).
=> refactor: Use a single transaction for all remote mediator operations

app/src/main/java/app/pachli/MainActivity.kt
Previous code would crash if the app resumed when the account selector was open, as `getPosition` would not return the position of a primary item (see https://github.com/mikepenz/MaterialDrawer/issues/2826 for details).
Fix this by directly checking the primary `itemAdapter` instead of using `getPosition`.
=> fix: Don't crash when resuming if the account selector was open

app/src/main/java/app/pachli/MainActivity.kt, app/src/main/java/app/pachli/components/drafts/DraftHelper.kt, app/src/main/java/app/pachli/components/drafts/DraftsViewModel.kt, core/database/src/main/kotlin/app/pachli/core/database/dao/DraftDao.kt, core/database/src/test/kotlin/app/pachli/core/database/dao/AccountEntityForeignKeyTest.kt
It won't be -1, which intent.pachliAccountId might be. Some of the functions called expect it not to be -1, and crash if it is.
=> revert: Use pachliAccountId in MainActivity

core/database/schemas/app.pachli.core.database.AppDatabase/17.json, core/database/src/main/kotlin/app/pachli/core/database/AppDatabase.kt, core/database/src/main/kotlin/app/pachli/core/database/dao/NotificationDao.kt, core/database/src/main/kotlin/app/pachli/core/database/model/NotificationEntity.kt
`NotificationDao.pagingSource` missed the `reportId` column and mis-soelled `report_ruleIds`, risking an NPE.
Fix that.
While I'm here, add suggested indices to `NotificationEntity`.
=> fix: Collect correct columns for NotificationReportEntity

app/src/main/java/app/pachli/components/search/SearchViewModel.kt, app/src/main/java/app/pachli/components/search/fragments/SearchStatusesFragment.kt
`SearchViewModel.pinAccount` actually pinned the status, so rename it to `pinStatus`.
=> change: Rename pinAccount to pinStatus

app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt
A previous change inadvertently removed the line that notified the timeline adapter of changes, so the UI wasn't refresh after e.g. boosting or favouriting a post.
=> fix: Update UI on boosts, etc

app/src/main/java/app/pachli/components/notifications/NotificationsViewModel.kt, app/src/main/java/app/pachli/components/timeline/CachedTimelineRepository.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/CachedTimelineViewModel.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/NetworkTimelineViewModel.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt, app/src/main/java/app/pachli/components/viewthread/ViewThreadViewModel.kt, app/src/test/java/app/pachli/components/timeline/StatusMocker.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/StatusRepository.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/notifications/NotificationsRepository.kt, core/database/schemas/app.pachli.core.database.AppDatabase/18.json, core/database/src/main/kotlin/app/pachli/core/database/AppDatabase.kt, core/database/src/main/kotlin/app/pachli/core/database/dao/NotificationDao.kt, core/database/src/main/kotlin/app/pachli/core/database/dao/StatusDao.kt, core/database/src/main/kotlin/app/pachli/core/database/dao/TimelineDao.kt, core/database/src/main/kotlin/app/pachli/core/database/model/StatusEntity.kt, core/database/src/main/kotlin/app/pachli/core/database/model/StatusViewDataEntity.kt, core/database/src/test/kotlin/app/pachli/core/database/dao/AccountEntityForeignKeyTest.kt
Previous code considered all non-primary-key properties of `StatusViewDataEntity` to be non-nullable.
This made setting the values more difficult than it needed to be, as a complete `StatusViewDataEntity` needed to be created first.
Make these properties nullable, so `@Upsert` with partial data POJOs can be used to update them.
Centralise the update code in `StatusRepository`. This also removes some duplicate code.
=> refactor: Simplify and centralise updates to StatusViewDataEntity

app/src/test/java/app/pachli/components/timeline/CachedTimelineRemoteMediatorTest.kt, app/src/test/java/app/pachli/components/timeline/NetworkTimelinePagingSourceTest.kt, app/src/test/java/app/pachli/components/timeline/NetworkTimelineRemoteMediatorTest.kt, app/src/test/java/app/pachli/components/viewthread/ViewThreadViewModelTest.kt, core/testing/build.gradle.kts, core/testing/src/main/kotlin/app/pachli/core/testing/fakes/FakeStatus.kt
Rename the functions to be more accurate (they return fakes, not mocks).
Move the functions to core.testing so they're available to tests in other modules.
=> change: Move / rename StatusMocker to core.testing / FakeStatus

core/database/schemas/app.pachli.core.database.AppDatabase/19.json, core/database/src/main/kotlin/app/pachli/core/database/AppDatabase.kt, core/database/src/main/kotlin/app/pachli/core/database/di/DatabaseModule.kt
A planned change adds an FK constraint between `StatusEntity` and `AccountEntity`.
This may cause a crash if the constraint is added and any existing `StatusEntity` reference non-existent `AccountEntity`. So delete them now.
=> change: Ensure DB contains no StatusEntity referencing non-existent AccountEntity

app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt, app/src/test/java/app/pachli/components/timeline/CachedTimelineViewModelTestStatusFilterAction.kt, app/src/test/java/app/pachli/components/timeline/NetworkTimelineViewModelTestStatusFilterAction.kt
Split `StatusAction` to `InfallibleStatusAction` and `FallibleStatusAction` to more accurately match their details.
Move `TranslateUndo` to `InfallibleStatusAction`.
=> refactor: Introduce {In}FallibleStatusAction

gradle.properties
Newer gradle is sometimes crashing with the message:
> Something has been appended to this collector already
Per https://youtrack.jetbrains.com/issue/KT-74394/KGP-isolated-projects-Something-has-been-appended-to-this-collector-already
this setting resolves it.
=> build: Work around "Something has been appended to this collector already"

app/src/main/java/app/pachli/components/viewthread/edits/ViewEditsAdapter.kt, app/src/main/java/app/pachli/components/viewthread/edits/ViewEditsViewModel.kt, core/ui/src/main/kotlin/app/pachli/core/ui/LinkHelper.kt, core/ui/src/main/kotlin/app/pachli/core/ui/NoUnderlineURLSpan.kt
Previous code used `unicodeWrap` to add the directional isolates, which returns a `String`. This overwrites any existing spans in the text, and in particular, the spans that marked insertions or deletions.
The effect was to remove the insert/delete markup for hashtags (and probably mentions) when viewing edits to a status.
Fix this by avoiding `unicodeWrap` in this case and adding the isolates to the spanned text.
While I'm here, cleanup up spoiler text wrangling in edits.
=> fix: Highlight modified hashtags when viewing status edits

app/src/main/java/app/pachli/components/account/AccountActivity.kt, app/src/main/res/menu/account_toolbar.xml, app/src/main/res/values/strings.xml, feature/about/src/main/res/values-en-rGB/strings.xml, feature/about/src/main/res/values-es/strings.xml, feature/about/src/main/res/values-fi/strings.xml, feature/about/src/main/res/values-ga/strings.xml, feature/about/src/main/res/values-gl/strings.xml, feature/about/src/main/res/values-kab/strings.xml, feature/about/src/main/res/values-lt/strings.xml, feature/about/src/main/res/values-nb-rNO/strings.xml, feature/about/src/main/res/values-nl/strings.xml, feature/about/src/main/res/values-pl/strings.xml, feature/about/src/main/res/values-sk/strings.xml, feature/about/src/main/res/values-zh-rCN/strings.xml, feature/about/src/main/res/values-zh-rHK/strings.xml, feature/about/src/main/res/values-zh-rTW/strings.xml, feature/about/src/main/res/values/strings.xml
The account screen allows the user to refresh the account info (avatar, bio, etc), or whichever timeline is showing at the bottom of the screen.
Both the menu items were labelled "Refresh". Change the ID and label of the first one to "Refresh account".
While I'm here there were duplicate `action_refresh` strings in `feature/about`. Remove or move them as appropriate.
Fixes #1295
=> fix: Avoid duplicate "Refresh" menus, rename to "Refresh account"

app/src/main/java/app/pachli/components/timeline/NetworkTimelineRepository.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/NetworkTimelineViewModel.kt
When a status is partially filtered ("Hide with a warning"), its "Show anyway" button would be no-op on some timelines, like "Trending posts" or a user's profile.
It turns out the functionality was broken on `NetworkTimelineViewModel/Repository`. The call to `NetworkTimelineViewModel.clearWarning()` wasn't having an effect because `repository.invalidate()` wasn't being called, although it was present on all other methods that also made use of `repository.updateActionableStatusById()` (`handleFavEvent()`, `handleBookmarkEvent()` and `handlePinEvent()`).
Instead of just adding `repository.invalidate()` to `clearWarning()`, I preferred to remove the call from the other methods and move it inside `NetworkTimelineRepository.updateActionableStatusById()`. This should prevent something similar …
=> fix: Invalidate NetworkTimelineRepository after clearing status filter

core/database/src/main/kotlin/app/pachli/core/database/AppDatabase.kt, core/database/src/main/kotlin/app/pachli/core/database/di/DatabaseModule.kt
The 10 -> 11 database migration adds FK constraints with `AccountEntity.id` as the parent.
Because of previous bugs there may be orphaned data in some tables that references accounts that no longer exist in `AccountEntity`. This causes a crash during migration.
This migration was previously automatic. Rewrite it to be manual, by copying the code that was previously generated and inserting explcit `DELETE` statements ahead of the migration to remove the orphaned rows.
Fixes #1320
=> fix: Remove old account data before creating FK constraints

.github/workflows/upload-orange-release-google-play.yml
To create the release in `pachli-android-current` the workflow needs a PAT with `write` permission to the `contents` scope on that repository.
That PAT has been created and set as a repository secret here, called `PACHLI_ANDROID_CURRENT_CONTENTS_PAT`. Pass it as the token the workflow will use.
=> ci: Use a personal access token to write to pachli-android-current

.github/workflows/upload-orange-release.yml, app/src/github/kotlin/app/pachli/updatecheck/UpdateCheck.kt
Update CI for the orange / Pachli Current release to build an APK specifically for Github and upload that to the `pachli-android-current` repository.
Modify the `UpdateCheck` code to look in `pachli-android-current` if it's the Pachli Current build.
=> feat: Deploy/fetch Pachli Current from Github pachli-android-current repository

feature/about/build.gradle.kts, gradle/libs.versions.toml
This includes https://github.com/mikepenz/AboutLibraries/pull/1056 which disables `generated` metadata, so remove our override which does the same.
=> fix(deps): update aboutlibraries to v11.6.3

app/src/main/java/app/pachli/components/preference/accountfilters/AccountConversationFiltersPreferenceDialogFragment.kt, app/src/main/java/app/pachli/components/preference/accountfilters/AccountNotificationFiltersPreferencesDialogFragment.kt, app/src/main/java/app/pachli/components/preference/accountfilters/BaseAccountFiltersPreferencesDialogFragment.kt, app/src/main/res/values/strings.xml
Different languages may need different labels for the options based on whether the filter will affect Notifications or Conversations.
Fixes #1348
=> change: Use different strings for labels in account filter dialogs

.github/workflows/upload-orange-release.yml
Github doesn't always sort the releases sensibly per the discussion at https://github.com/orgs/community/discussions/8226, so explicitly mark each release from this workflow as the latest release.
=> ci: Always mark pachli-android-current release as latest

.github/workflows/upload-orange-release.yml
Previous code used the first line of the most recent commit as the contents of the "whatsnew" file.
Expand that, by:
1. Fetch the commit ID associated with the most recent Orange release.
2. Fetch the first line of each log since then, and filter for uniqueness (e.g., to filter out multiple updates to a single language).
3. If the generated file size is > 500 bytes then cut it down to 485 bytes and append "... and more"
=> ci: Generate a more complete "What's New" file for Pachli Current releases

core/network/src/main/kotlin/app/pachli/core/network/model/Report.kt
=> fix: Correctly parse `action_taken` and similar in report notifications

core/network/src/main/kotlin/app/pachli/core/network/model/Report.kt
The report `forwarded` property is not supposed to be nullable, but Mastodon will return null in some cases. When that happens assume the value is actually `false` so the JSON parses correctly.
Fixes #1352
=> fix: Allow Report notifications with a null `forwarded` property

gradle/libs.versions.toml
The publisher also changed in this release.
=> fix(deps): update dependency com.github.canhub:android-image-cropper to v4.3.3

app/src/main/java/app/pachli/components/compose/ComposeViewModel.kt
Previous code tried to use the media update API to update captions when editing a status, but that only works if the status has not been posted yet.
When editing a status the caption edits go through the status edit API, so just record the new caption and exit early.
Fixes #1380
=> fix: Support editing captions of uploaded images

app/src/main/java/app/pachli/components/conversation/ConversationsViewModel.kt, app/src/main/java/app/pachli/components/viewthread/ThreadAdapter.kt, app/src/main/java/app/pachli/components/viewthread/ViewThreadViewModel.kt, app/src/test/java/app/pachli/components/viewthread/ViewThreadViewModelTest.kt, core/model/src/main/kotlin/app/pachli/core/model/ContentFilters.kt, core/network/src/main/kotlin/app/pachli/core/network/model/FilterContext.kt
Previous code:
- Applied filters to private messages.
- Ignored filters when showing the "detailed" message in a thread.
- Used the "notifications" context when filtering threads instead of the correct "conversations" context.
Fix these issues.
Fixes #1385
=> fix: Filter correctly in threads and private messages

app/src/main/java/app/pachli/components/filters/EditContentFilterViewModel.kt
Content filters make sense if they're applied to all contexts.
Otherwise you can have a situation where e.g., a status that @-mentions you is filtered from the Home timeline, but the notification about the mention is not filtered from the Notifications timeline.
To make this easier for users change the default behaviour for the filter contexts for new filters. Previously all contexts were disabled and the user would choose which contexts to enable.
Now all contexts are enabled, and the user chooses which ones to disable.
Fixes #1383
=> feat: Make new content filters default to active in all contexts

core/network/src/main/kotlin/app/pachli/core/network/retrofit/MastodonApi.kt
Content filters are created with a form-encoded POST request. The Mastodon API defines these in a way that can't be replicated with Retrofit's normal mechanisms for defining an API (including using the `@FormUrlEncoded annotation`), so `NewContentFilterConverterFactory` converts the `NewContentFilter` object to the body of the request.
However, for some servers (at least, GoToSocial) the content-type header is required. That's normally provided by the `@FormUrlEncoded` annotation, but that can't be used here.
So provide the header directly in the API definition.
Fixes #1375
=> fix: Create filters with the correct content-type

core/ui/src/main/kotlin/app/pachli/core/ui/ClickableSpanTextView.kt
Crash logs show a `StringIndexOutOfBoundsException` here, possibly because the case where `getSpanStart()` or `getSpanEnd()` return `-1` (for reasons unknown).
Handle that case, and don't set a title for the chooser if it happens.
=> fix: Prevent crash on long press if span is not attached

core/ui/src/main/kotlin/app/pachli/core/ui/SetStatusContent.kt
Adjust Markdown pre-processing to provide better results in two cases.
1. Trim leading spaces immediately after a `<p>` element. This prevents quoted regions from starting with leading whitespace (effectively requiring `>` before each quoted line).
2. Escape `~~~`, so only three-backticks can be used to start a fenced code block.
=> fix: Handle initial whitespace and `~~~` when parsing Markdown

core/ui/build.gradle.kts, core/ui/src/main/kotlin/app/pachli/core/ui/SetStatusContent.kt, gradle/libs.versions.toml
Enable the Latex Markdown plugin, which renders Latex in `$$` delimited blocks.
Re-write `\(` / `\{` and `)` / `\}` (which Mathstodon uses as Latex markers) to `$$` to trigger the Latex processing.
=> feat: Render Mathstodon Latex formulae when Markdown is enabled

app/src/main/java/app/pachli/ViewMediaActivity.kt, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-ga/strings.xml, app/src/main/res/values-gl/strings.xml, app/src/main/res/values-nb-rNO/strings.xml, app/src/main/res/values-nn/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-ta/strings.xml, app/src/main/res/values/strings.xml
Previous code executed an OkHttp call without catching the exception that could occur if the call failed.
Rewrite this to use `runSuspendCatching` and convert the error response to an `ApiError`. This gives a better error message using `fmt()`, and the error message format string can be simplified.
=> fix: Don't crash if download error happens when sharing media

app/src/main/java/app/pachli/components/conversation/ConversationsFragment.kt, app/src/main/java/app/pachli/components/notifications/NotificationsFragment.kt, app/src/main/java/app/pachli/components/notifications/NotificationsViewModel.kt, app/src/main/java/app/pachli/components/timeline/CachedTimelineRepository.kt, app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/CachedTimelineViewModel.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/NetworkTimelineViewModel.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt, app/src/main/java/app/pachli/interfaces/StatusActionListener.kt, app/src/main/java/app/pachli/usecase/TimelineCases.kt, app/src/test/java/app/pachli/components/notifications/NotificationsViewModelTestStatusFilterAction.kt, app/src/test/java/app/pachli/components/timeline/NetworkTimelineViewModelTestBase.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/StatusRepository.kt, core/data/src/test/kotlin/app/pachli/core/data/repository/StatusRepositoryTest.kt, core/database/src/main/kotlin/app/pachli/core/database/dao/StatusDao.kt, core/database/src/main/kotlin/app/pachli/core/database/dao/TranslatedStatusDao.kt, core/network/src/main/kotlin/app/pachli/core/network/model/Poll.kt
Previous code could translate statuses in the home timeline and threads, but nowhere else.
Extend this support to almost all timelines, in particular:
- Notifications
- Local and federated timelines
- Trending
- Bookmarks
- Favourites
Places where translation is not possible are still:
- Conversations; translation isn't permitted on statuses with `direct` visibility
- Search results; more work has to be done there
To do this the primary adjustments are to `TimelineViewModel` and `NetworkTimelineViewModel`. Previously `TimelineViewModel` contained code that more properly belonged in `CachedTimelineViewModel`; that code has been moved there, and the actions code in `{Cached,Network}TimelineViewModel` is now more explicit.
This also fixes a long-standing TODO in `TimelineFragment`, which was …
=> feat: Support translation throughout the app

app/src/main/java/app/pachli/components/compose/view/TootButton.kt, app/src/main/res/values/strings.xml, core/network/src/main/kotlin/app/pachli/core/network/model/Status.kt
If the user was using a small screen the "Toot" button (when writing a post) had no text on it, and with no content description there was nothing for TalkBack to read out.
Fix this by always setting the content description. Include the visibility in the content description so the ramifications of pressing the button are always clear to the user.
=> fix: Always set an accessible description on the "Toot" button

app/src/main/java/app/pachli/adapter/StatusBaseViewHolder.kt, app/src/main/java/app/pachli/util/ListStatusAccessibilityDelegate.kt
Previous change overwrote the entire content description built in `setContentDescriptionForStatus`, so some content was dropped from the description.
Revert that, and use the parsed content in `setContentDescriptionForStatus` to get the right effect.
=> fix: Use parsed status content when building contentDescription

app/src/main/java/app/pachli/components/report/ReportActivity.kt, app/src/main/java/app/pachli/components/report/ReportViewModel.kt, app/src/main/java/app/pachli/components/report/adapter/StatusViewHolder.kt, app/src/main/java/app/pachli/components/report/adapter/StatusesAdapter.kt, app/src/main/java/app/pachli/components/report/fragments/ReportDoneFragment.kt, app/src/main/java/app/pachli/components/report/fragments/ReportStatusesFragment.kt
The report UI could get stuck loading account info. Re-write to use the information provided in the initial intent so it's not a problem.
Also, use `SetStatusContent` so the user's choice of Markdown rendering is respected.
=> fix: Stop the report UI from sometimes hanging, honour Markdown setting

app/src/main/java/app/pachli/components/compose/ComposeViewModel.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/AccountManager.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/Loadable.kt
Rewrite `Loading` as a data object (no constructor parens required to create) with a `Nothing` generic type.
Implement `.get()` which returns the `.Loaded` value, or null if there isn't one.
Update use sites.
=> refactor: Improve `Loadable` interface ergnomonics

app/src/main/java/app/pachli/components/report/ReportActivity.kt, app/src/main/java/app/pachli/components/report/ReportViewModel.kt, app/src/main/java/app/pachli/components/report/Screen.kt, app/src/main/java/app/pachli/components/report/fragments/ReportDoneFragment.kt, app/src/main/java/app/pachli/components/report/fragments/ReportNoteFragment.kt, app/src/main/java/app/pachli/components/report/fragments/ReportStatusesFragment.kt, core/network/src/main/kotlin/app/pachli/core/network/model/Relationship.kt
Changes include:
- Use `Result<V, E>` for carrying success/error state.
- Use `PachliError` for reporting errors, including formatted error messages.
- Use `bind()` as the function name that starts binding values to the UI.
- Use `Loadable` to track data during the loading process.
- Make network calls when flows are collected from the view model, not the `init` block.
- Move navigation logic in to the view model.
=> refactor: Use flows instead of observables in the "Report" code

app/src/main/res/values-es/strings.xml
Currently translated at 100.0% (756 of 756 strings)
Translation: Pachli/App : Main
Translate-URL: https://hosted.weblate.org/projects/pachli/app-main/es/ (cherry picked from commit d3ae37d0342a01a6b84870981c295cd63b8f23a2)
=> fix(l10n): Update Spanish translations

app/src/main/java/app/pachli/components/followedtags/FollowedTagsActivity.kt, app/src/main/java/app/pachli/components/followedtags/FollowedTagsAdapter.kt, app/src/main/java/app/pachli/components/followedtags/FollowedTagsViewModel.kt, app/src/main/res/layout/activity_followed_tags.xml, app/src/main/res/layout/item_followed_hashtag.xml, app/src/main/res/values/strings.xml
Use the statistics in two places:
1. Most obviously, as a second line of detail for each hashtag in the list.
2. When adding a new hashtag, sort the list of hashtags by the usage count
=> feat: Show hashtag statistics in the Followed Tags screen

app/src/main/java/app/pachli/components/timeline/viewmodel/NetworkTimelineRemoteMediator.kt
Ensures I don't waste another 30 minutes wondering why the debug build is crashing.
=> change: Add a link to the Mastodon bug for pinned statuses

app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/NetworkTimelinePagingSource.kt
This was earlier behaviour, but by accident. b08a0ba28218 broke this when database lookups were added in `NetworkTimelineViewModel.getStatuses()`.
The data didn't need to be used -- simply making the database lookup was enough to lose the race. This could also be dependent on network timing and the speed the remote server returned results, so never showed up in local tests.
This changed the timing for when results were returned, resulting in `state.anchorPosition` being much lower down the list (i.e,. instead of being e.g., `2` it might be `39`.
=> fix: Set initial reading position for non-cached timelines to the top

app/src/test/java/app/pachli/components/compose/ComposeActivityTest.kt, app/src/test/java/app/pachli/components/timeline/CachedTimelineRemoteMediatorTest.kt, core/data/src/test/kotlin/app/pachli/core/data/repository/InstanceInfoRepositoryTest.kt, core/data/src/test/kotlin/app/pachli/core/data/repository/filtersRepository/BaseContentFiltersRepositoryTest.kt, core/database/src/androidTest/kotlin/app/pachli/core/database/dao/TimelineDaoTest.kt, core/database/src/test/kotlin/app/pachli/core/database/dao/AccountEntityForeignKeyTest.kt, core/database/src/test/kotlin/app/pachli/core/database/dao/NotificationEntityForeignKeyTest.kt
Tests were occasionally failing with exceptions indicating the database was not available. Experimentation suggests the code that was closing the database after each test was the cause, possibly because it's running in Retrofit rather than a device.
=> test: Prevent exceptions, don't explicitly close the injected database

PRIVACY.md, app/lint-baseline.xml, app/src/main/AndroidManifest.xml, app/src/main/res/xml/backup_rules.xml, app/src/main/res/xml/data_extraction_rules.xml, test-cloud-backup.sh
- Add a copy of the test script to verify backups are working
- Cover backups in the privacy policy
Fixes #961
=> feat: Enable client-side encrypted cloud backups

core/network/src/main/kotlin/app/pachli/core/network/json/InstantJsonAdapter.kt, core/network/src/main/kotlin/app/pachli/core/network/model/Report.kt
Two bugs here.
The first is that `Report.actionTakenAt` wasn't marked as nullable when it should be.
The second is the adapter that converts from JSON to `Instant` wasn't written to allow null values.
Together these caused notification loading to fail and display an error.
Fix both of those issues.
Fixes #1469
=> fix: Don't error on nullable `Report.actionTakenAt` property

app/src/main/java/app/pachli/components/viewthread/ViewThreadFragment.kt, app/src/main/java/app/pachli/components/viewthread/ViewThreadViewModel.kt
Previous code didn't fetch the translation state or data from the database when viewing a thread, so statuses that were translated on a timeline were not translated in a thread. This also applied to any translated media descriptions.
Fix this by fetching the local translation info and merging with the network data, and by ensuring translated media descriptions are passed in onViewMedia.
Fixes #1483
=> fix: Show translated posts / media descriptions when viewing threads

core/network/src/main/kotlin/app/pachli/core/network/model/Notification.kt
Previous code listed them in full, omitting `UNKNOWN`. This makes it possible to inadvertently forget to update this list when new notification types are created.
Rewrite to use all types, explicitly filtered to omit `UNKNOWN`, to prevent this.
=> refactor: Simplify list of visible notification types

feature/login/src/main/kotlin/app/pachli/feature/login/LoginActivity.kt, feature/login/src/main/kotlin/app/pachli/feature/login/LoginWebViewActivity.kt
Rename to Code and Error so they don't class with the `Result` type used through the rest of the code.
=> refactor: Rename LoginResult subclasses

.github/workflows/ci.yml
Emulator log messages report that not specifying a metrics option will soon block the launch, so explicitly opt out of reporting metrics.
While here make sure the emulator is launched with consistent options, and disable animations in the emulator launched to run the tests.
=> ci: Disable metrics when launching emulator

core/common/src/main/kotlin/app/pachli/core/common/util/Lazy.kt
Previous code meant type inference didn't always work with `unsafeLazy` because it was generic over `<T : Any>`.
Make it generic over `<T>` (just like `lazy`) to fix this.
=> change: Improve type inference for unsafeLazy

app/src/main/java/app/pachli/components/notifications/domain/EnableAllNotificationsUseCase.kt
What used to be parameters to methods are now injected in to the constructor.
=> refactor: Remove unnecessary params from EnableAllNotificationsUseCase methods

app/src/main/res/layout/status_poll.xml
If the "Show votes" button is hidden (e.g., because no one has voted on the poll) the constraint layout default behaviour is to centre the "Vote" button, which is not it's normal position.
Set an explicit horizontal bias to fix this.
=> fix: Start-align "Vote" button's position

app/src/main/java/app/pachli/MainActivity.kt
Move all the coroutines that launch when `RESUMED` to a single `repeatOnLifecycle` block, instead of needlessly repeating it.
=> change: Use a single repeatOnLifecycle(RESUMED) in MainActivity

app/src/main/java/app/pachli/components/account/media/AccountMediaFragment.kt, app/src/main/java/app/pachli/components/conversation/ConversationsFragment.kt, app/src/main/java/app/pachli/components/preference/AccountPreferencesFragment.kt, app/src/main/java/app/pachli/components/preference/PreferencesFragment.kt, app/src/main/java/app/pachli/components/report/fragments/ReportStatusesFragment.kt, app/src/main/java/app/pachli/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/app/pachli/components/trending/TrendingLinksFragment.kt, app/src/main/java/app/pachli/fragment/SFragment.kt, core/activity/src/main/kotlin/app/pachli/core/activity/extensions/FragmentExtensions.kt, core/activity/src/main/kotlin/app/pachli/core/activity/extensions/IntentExtensions.kt
Allows all fragments to use this functionality, not just SFragment.
Use a slide transition when replying, editing, or viewing tags.
=> change: Provide startActivityWith{Default}Transition for fragments

app/src/main/java/app/pachli/components/compose/ComposeActivity.kt
Previous code saved the URI to save camera images to, but didn't restore it early enough. If `ComposeActivity` was destroyed and recreated `onActivityResult` could be called before `photoUploadUri` was restored (so still null), resulting in an NPE.
Move the state restoration code earlier in `onCreate` so it's guaranteed to have run.
=> fix: Don't crash if ComposeActivity is destroyed while taking a picture

app/src/main/java/app/pachli/components/compose/ComposeActivity.kt, app/src/main/res/layout/activity_compose.xml
Poll previews had their layout params overwritten, which meant they were laid out at the top of the view, overlapping the content.
Fix this.
=> fix: Display poll previews correctly

app/src/main/java/app/pachli/components/compose/ComposeActivity.kt
Previous colour choice was not visible in dark mode. Instead of explicitly setting a colour, clear the colour filter, which will fall back to whatever the default "disabled" colour is.
=> fix: Improve colours when compose buttons are enabled

core/database/src/main/kotlin/app/pachli/core/database/model/AccountEntity.kt
This is likely to give the user a better initial experience, as the set of trending statuses is probably more interesting than the unfiltered "Local" stream.
=> feat: Replace Local timeline with Trending in default tabs

core/network/src/main/kotlin/app/pachli/core/network/json/InstantJsonAdapter.kt, core/network/src/main/kotlin/app/pachli/core/network/json/LenientRfc3339DateJsonAdapter.kt, core/network/src/test/kotlin/app/pachli/core/network/json/Rfc3339DateTest.kt
Some servers don't include the (mandatory) timezone information. This was already supported by `LenientRfc3339DateJsonAdapter` when parsing to a `Date`, support it when parsing to an `Instant` too.
Test both adapters with the same data and ensure they return the same results for the same input.
=> feat: Parse Instants from servers that don't include the timezone

app/src/main/java/app/pachli/MainActivity.kt
Glide throws an undocumented/unnecessary exception here, which is caught and ignored.
=> fix: Don't crash when cancelling images during activity cancellation

app/src/main/java/app/pachli/adapter/StatusBaseViewHolder.kt, app/src/main/java/app/pachli/adapter/StatusDetailedViewHolder.kt, app/src/main/java/app/pachli/components/account/media/AccountMediaGridAdapter.kt, app/src/main/java/app/pachli/components/compose/ComposeAutoCompleteAdapter.kt, app/src/main/java/app/pachli/components/conversation/ConversationViewHolder.kt, app/src/main/java/app/pachli/components/notifications/NotificationHelper.kt, app/src/main/java/app/pachli/components/notifications/StatusNotificationViewHolder.kt, app/src/main/java/app/pachli/util/ListStatusAccessibilityDelegate.kt
Destructuring (`val (_, _, x, y, _, _, z, _, _) = someObject`) is dangerous, because if the order of the properties in `someObject` change without changing the types you have a runtime bug instead of a compile time error.
Replace this with explicit variable creation and assignment for each used property. Noticed some places where the actionable status is the correct choice, update those call sites.
=> refactor: Don't destructure large classes

app/src/main/java/app/pachli/components/compose/ComposeActivity.kt, app/src/main/java/app/pachli/components/compose/ComposeViewModel.kt, app/src/main/res/layout/activity_compose.xml
`ComposeActivity` had variables, functions, and view IDs that didn't accurately reflect what they did, making it more difficult to read the code.
Rename many of them to be clearer.
While here:
- Add documentation comments to many functions.
- Early return from some functions, instead of nested `if` statements.
- Remove unused function parameters.
=> change: Rename code in ComposeActivity and related code

app/src/main/java/app/pachli/components/conversation/ConversationsRemoteMediator.kt, app/src/main/java/app/pachli/components/notifications/NotificationsFragment.kt, app/src/main/java/app/pachli/components/notifications/NotificationsViewModel.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/CachedTimelineRemoteMediator.kt, app/src/test/java/app/pachli/components/notifications/NotificationsViewModelTestClearNotifications.kt, app/src/test/java/app/pachli/components/timeline/CachedTimelineRemoteMediatorTest.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/notifications/NotificationsRemoteMediator.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/notifications/NotificationsRepository.kt
Previously, when the user decided to clear all notifications they were deleted from the server but the local cache was not cleared (because the remote mediator returned early if they were no results on a refresh), so Pachli continued to show the (now deleted) notifications.
Fix that -- always delete the notifications.
While I'm here, make the "enabled" state of the "Clear notifications" menu item contingent on whether there are any notifications available to delete, and update CachedTimelineRemoteMediator and ConversationsRemoteMediator to behave the same.
Fixes #1582
=> fix: Delete cached notifications when deleting server notifications

core/navigation/src/main/kotlin/app/pachli/core/navigation/Navigation.kt
Previous code didn't include the account's emojis when replying, which meant the display name of the account being replied to might show emoji shortcodes instead of the images.
Fix this by including the account's emojis when constructing the `InReplyTo.Status` object.
=> fix: Show an account's emoji's when replying

app/src/main/java/app/pachli/components/notifications/PushNotificationHelper.kt, app/src/main/java/app/pachli/components/notifications/domain/EnableAllNotificationsUseCase.kt
Had a user report of a crash with the following stack trace:
```
android.content.res.Resources$NotFoundException: Resource ID #0x0
at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:285)
at android.content.res.Resources.loadXmlResourceParser(Resources.java:2570)
at android.content.res.Resources.getLayout(Resources.java:1285)
at android.view.LayoutInflater.inflate(LayoutInflater.java:460)
at android.view.LayoutInflater.inflate(LayoutInflater.java:413)
at androidx.appcompat.app.AlertDialog$Builder.create(SourceFile:145)
at app.pachli.components.notifications.PushNotificationHelperKt.a(SourceFile:239)
...
```
That's the dialog creation in `chooseUnifiedPushDistributor()`.
That *might* be because the context used to launch the dialog is an `ApplicationContext` (based on online …
=> fix: Don't crash when showing dialog to choose a push provider

core/ui/src/main/kotlin/app/pachli/core/ui/CustomEmojiHelper.kt
Previous code return `Size(0, 0)`, which crashes when trying to load into the target (Glide refuses to load). Fix this by returning the default size.
=> fix: Don't crash if emoji drawable is null

core/database/schemas/app.pachli.core.database.AppDatabase/26.json, core/database/src/main/kotlin/app/pachli/core/database/AppDatabase.kt, core/model/src/main/kotlin/app/pachli/core/model/Announcement.kt, core/model/src/main/kotlin/app/pachli/core/model/Attachment.kt, core/model/src/main/kotlin/app/pachli/core/model/Card.kt, core/model/src/main/kotlin/app/pachli/core/model/Emoji.kt, core/model/src/main/kotlin/app/pachli/core/model/FilterResult.kt, core/model/src/main/kotlin/app/pachli/core/model/Poll.kt, core/model/src/main/kotlin/app/pachli/core/model/Status.kt, core/model/src/main/kotlin/app/pachli/core/model/Timeline.kt, core/model/src/main/kotlin/app/pachli/core/model/TimelineAccount.kt, core/model/src/main/kotlin/app/pachli/core/model/Translation.kt, core/model/src/main/kotlin/app/pachli/core/model/UserListRepliesPolicy.kt
These were a holdover from when these were the network classes and serialised directly to the database, and can be removed now.
The exceptions are classes where the database holds user data and is not just a cache of remote data (e.g., `DraftEntity` references `DraftAttachment` `NewPoll`, both of which may already be serialised to the database).
For the classes where this can be done perform the removal. Because the database cache may now contain data in the obsolete format clear the affected cache tables. This also fixes a potential crash if any of the stale data is loaded (e.g., reading obsolete data from `StatusEntity` when loading a thread).
=> fix: Remove custom @Json custom names from most core.model classes

app/lint-baseline.xml, feature/manageaccounts/lint-baseline.xml, feature/manageaccounts/src/main/res/color/account_selector.xml, feature/manageaccounts/src/main/res/layout/item_pachli_account.xml
API 24 devices (at least, possibly some newer API levels) don't want `android:background` to be a color statelist, crashing because the XML resource inflater expects to find a drawable instead of a colour.
Work around this by setting the colour to the surface colour, and using the statelist as the background tint.
=> fix: Don't crash when managing accounts on older API devices

app/src/main/java/app/pachli/fragment/ViewVideoFragment.kt, app/src/main/res/layout/fragment_view_video.xml
Playback controls can appear before the media is ready and the controller is configured. They're then replaced (which moves them up the screen) with correct controls, so the UI appears to "stutter" as this happens.
Work around this by only setting `useController` when the media is ready to start.
=> fix: Prevent visual "stutter" when first showing playback controls

app/src/main/java/app/pachli/ViewMediaActivity.kt, app/src/main/java/app/pachli/fragment/ViewMediaFragment.kt, app/src/main/java/app/pachli/fragment/ViewVideoFragment.kt, app/src/main/java/app/pachli/pager/ImagePagerAdapter.kt
Previously the `AudioBecomingNoisyReceiver` was registered in the fragment playing the video.
This works for statuses from Mastodon which can only have a single video attached. However, statuses from other networks may have multiple videos attached. The receiver would be registered by each video playing fragment and then unregistered when they pause/stop. Because the receiver is a singleton the second attempt to unregister it (if the status has two or more video attachments) would crash.
Fix this by moving the broadcast receiver to `ViewMediaActivity`. Implement the receiver as lifecycle observer so it can register/unregister itself without needing to modify `ViewMediaActivity` beyond instantiating the object.
Update `ViewMediaAdapter` to include an `onAudioBecomingNoisy` method to call …
=> fix: Don't crash unregistering AudioBecomingNoisyReceiver

app/src/main/java/app/pachli/pager/ImagePagerAdapter.kt
Previous code only notified the first fragment the transition ended, which meant that any subsequent fragments that showed video would never show the media controls -- they were waiting for a transition to complete that had already completed but they didn't know about.
Fix that by notifying the fragment every time it is bound.
=> fix: Show playback controls on video fragments after the first

app/src/main/java/app/pachli/ViewMediaActivity.kt, app/src/main/java/app/pachli/components/compose/ComposeActivity.kt, app/src/main/java/app/pachli/components/compose/MediaUploader.kt, app/src/main/java/app/pachli/components/drafts/DraftHelper.kt, app/src/main/java/app/pachli/components/search/fragments/SearchStatusesFragment.kt, app/src/main/java/app/pachli/fragment/SFragment.kt, app/src/main/java/app/pachli/util/MediaUtils.kt, app/src/main/java/app/pachli/util/UriExtensions.kt, core/domain/src/main/kotlin/app/pachli/core/domain/DownloadUrlUseCase.kt
Previous code did a lot of UI work on whatever happened to be the
active dispatcher. Refactor to run the work explicitly on `Dispatchers.IO`
to ensure it's off the main thread.
=> refactor: Move more IO code to Dispatchers.IO

core/navigation/src/main/kotlin/app/pachli/core/navigation/Navigation.kt
Previous code displayed the account's local part in the UI when replying.
Change to use `username` -- for local accounts this is still just the local part, for remote accounts it will include the domain. This is consistent with how handles are displayed in timelines.
=> fix: Show the account's username (includes domain) when replying

app/src/main/java/app/pachli/fragment/ViewImageFragment.kt
Previously you could zoom in on an image and it would appear edge-to-edge in immersive mode and you can scroll around. But the edge of the image might still appear under the camera cutouts in the display.
Add padding; the image can still be scrolled under the camera cutout, but the edge of the image can be moved away from it completely.
=> fix: Show large/zoomed images with padding to avoid insets

app/src/main/java/app/pachli/adapter/ReportNotificationViewHolder.kt, app/src/main/java/app/pachli/components/announcements/AnnouncementAdapter.kt, build-logic/convention/src/main/kotlin/AndroidLibraryConventionPlugin.kt, core/ui/src/main/kotlin/app/pachli/core/ui/CustomEmojiHelper.kt, core/ui/src/main/kotlin/app/pachli/core/ui/emoji/EmojiPickerView.kt
Custom lint checks weren't being applied to modules other than :app, so the detector to check for appropriate use of `Glide.with()` wasn't running over the other modules.
Fix that, and update a couple of call sites where a properly scoped `RequestManager` could be passed down.
=> fix: Use properly scoped Glide in more places

app/src/main/java/app/pachli/components/conversation/ConversationsRepository.kt, app/src/main/java/app/pachli/components/conversation/ConversationsViewModel.kt, app/src/main/java/app/pachli/components/notifications/NotificationsViewModel.kt, app/src/main/java/app/pachli/components/search/SearchViewModel.kt, app/src/main/java/app/pachli/components/timeline/CachedTimelineRepository.kt, app/src/main/java/app/pachli/components/timeline/NetworkTimelineRepository.kt, app/src/main/java/app/pachli/components/timeline/TimelineRepository.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/CachedTimelineViewModel.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/NetworkTimelineViewModel.kt, app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt, app/src/main/java/app/pachli/components/viewthread/ViewThreadViewModel.kt, app/src/main/java/app/pachli/fragment/SFragment.kt, app/src/main/java/app/pachli/usecase/TimelineCases.kt, app/src/test/java/app/pachli/components/notifications/NotificationsViewModelTestBase.kt, app/src/test/java/app/pachli/components/timeline/CachedTimelineViewModelTestBase.kt, app/src/test/java/app/pachli/components/timeline/NetworkTimelineViewModelTestBase.kt, app/src/test/java/app/pachli/components/viewthread/ViewThreadViewModelTest.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/OfflineFirstStatusRepository.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/StatusRepository.kt, core/data/src/main/kotlin/app/pachli/core/data/repository/notifications/NotificationsRepository.kt, core/data/src/test/kotlin/app/pachli/core/data/repository/StatusRepositoryTest.kt
Previous code that operated on timelines and statuses generally injected a repository for the timeline and `StatusRepository`, then had to remember which repository to use for which operation. In some cases the timeline repository included methods that just wrapped those in `StatusRepository`.
Simplify this. Now the goal is that viewmodels work with a single repository for the timeline they operate on. The `StatusRepository` methods have been moved to an interface, implemented by `OfflineFirstStatusRepository`.
The timeline repositories inject `OfflineFirstStatusRepository` as a constructor parameter and implement `StatusRepository` by delegating to the injected `OfflineFirstStatusRepository`.
Most viewmodels have been updated to do this. Some legacy ones which don't have a specific …
=> refactor: Implement StatusRepository in other repositories

app/src/main/java/app/pachli/adapter/StatusBaseViewHolder.kt, app/src/main/java/app/pachli/components/conversation/ConversationViewHolder.kt
The data is already present in the `viewData` passed to the method, so was redundant.
While I'm here, rename its use in the method to `showingMedia` as that more accurately describes what it is for.
=> refactor: Remove showingContent param from setMediaPreviews()

app/src/main/java/app/pachli/adapter/StatusBaseViewHolder.kt, core/ui/src/main/kotlin/app/pachli/core/ui/ImageLoadingHelper.kt
Previous code applied a background to avatars to ensure that partially transparent areas are fully opaque when drawing content under them. This happened before the avatar image was scaled for use.
Not sure why, but this has started to cause animated avatars to be displayed at the wrong size.
Fix the problem by only performing the compositing after the avatars have been scaled.
While I'm here, clean up an unnecessary pass of "null" as the value.
=> fix: Show animated avatars at correct size in timelines

app/src/google/kotlin/app/pachli/translation/MlKitTranslationService.kt, app/src/main/java/app/pachli/translation/Translation.kt
Previous code showed the language code, resulting in UI messages like:
> cannot translate from eu
Fix that to use the language code's `displayLanguage`, if available. Now the error message looks like:
> cannot translate from Basque
=> fix: Show source language name if translation is not supported

core/ui/src/main/kotlin/app/pachli/core/ui/AttachmentPreviewView.kt
Inadvertently dropped as part of
https://github.com/pachli/pachli-android/pull/1819.
Fixes #1826
=> fix: Scale attachment preview images correctly with `.centerInside()`

app/src/main/java/app/pachli/TabPreferenceActivity.kt, app/src/main/java/app/pachli/adapter/ReportNotificationViewHolder.kt, app/src/main/java/app/pachli/adapter/StatusBaseViewHolder.kt, app/src/main/java/app/pachli/adapter/StatusViewHolder.kt, app/src/main/java/app/pachli/components/compose/view/ProgressImageView.kt, app/src/main/java/app/pachli/components/conversation/ConversationsFragment.kt, app/src/main/java/app/pachli/components/notifications/NotificationsFragment.kt, app/src/main/java/app/pachli/components/notifications/StatusNotificationViewHolder.kt, app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt, app/src/main/java/app/pachli/components/trending/TrendingTagsFragment.kt
They do the same thing, but an upcoming change is going to move the use of SparkButton to `core.ui`. Refactoring now makes that future change smaller.
=> refactor: Replace SparkButton.Utils.dpToPx with TypedValueCompat.dpToPx

app/src/test/java/app/pachli/ContentFilterV1Test.kt, app/src/test/java/app/pachli/components/notifications/NotificationsViewModelTestBase.kt, app/src/test/java/app/pachli/components/notifications/NotificationsViewModelTestStatusFilterAction.kt, app/src/test/java/app/pachli/components/timeline/CachedTimelineRemoteMediatorTest.kt, app/src/test/java/app/pachli/components/timeline/CachedTimelineViewModelTestBase.kt, app/src/test/java/app/pachli/components/timeline/CachedTimelineViewModelTestStatusFilterAction.kt, app/src/test/java/app/pachli/components/timeline/NetworkTimelineViewModelTestBase.kt, app/src/test/java/app/pachli/components/timeline/NetworkTimelineViewModelTestStatusFilterAction.kt, core/data/src/test/kotlin/app/pachli/core/data/repository/StatusRepositoryTest.kt, core/testing/src/main/kotlin/app/pachli/core/testing/extensions/AppDatabaseExtensions.kt, core/testing/src/main/kotlin/app/pachli/core/testing/fakes/FakeStatus.kt
Tests were playing a bit fast and loose with whether or not data needed to exist in the in-memory database when testing. Fix this by finishing the work of consolidating the functions that create fake statuses for testing, and inserting these into the database before tests run.
=> refactor: Create statuses and accounts in AppDatabase when testing

core/database/src/main/kotlin/app/pachli/core/database/dao/StatusDao.kt
`IIF()` isn't available in the SQLite version on some devices, causing a crash. Replace with a more verbose `CASE`, which is available.
=> fix: Don't crash on older devices, use CASE instead of IIF
