README.md

Update missing or incorrect information in README.md
- Link to Weblate with a badge
- Link to Play and F-Droid stores
- Correct the link to the list of releases
- Link to CONTRIBUTING.md
Fixes #13

docs: Update badges and fix links in README.md

---

app/lint-baseline.xml
app/src/main/java/app/pachli/components/account/AccountActivity.kt
app/src/main/java/app/pachli/components/accountlist/AccountListFragment.kt
app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt
app/src/main/java/app/pachli/components/trending/TrendingActivity.kt
app/src/main/java/app/pachli/components/trending/TrendingLinksFragment.kt
app/src/main/java/app/pachli/components/trending/TrendingTagsFragment.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_trending.xml

fix: statusbar background

---

app/lint-baseline.xml
app/src/main/java/app/pachli/AboutActivity.kt
app/src/main/res/layout/activity_about.xml
app/src/main/res/values/strings.xml

Google requires an in-app link to the privacy policy.

feat: Link to the privacy policy from "About"

---

app/build.gradle
app/lint-baseline.xml
app/src/main/java/app/pachli/components/preference/PreferencesActivity.kt
app/src/main/java/app/pachli/fragment/ViewVideoFragment.kt
app/src/main/java/app/pachli/view/ClickableSpanTextView.kt
app/src/main/java/app/pachli/view/GraphView.kt
app/src/test/java/app/pachli/FilterV1Test.kt
app/src/test/java/app/pachli/StatusComparisonTest.kt
app/src/test/java/app/pachli/components/notifications/NotificationsPagingSourceTest.kt
app/src/test/java/app/pachli/components/notifications/NotificationsViewModelTestBase.kt
app/src/test/java/app/pachli/components/timeline/CachedTimelineRemoteMediatorTest.kt
app/src/test/java/app/pachli/components/timeline/CachedTimelineViewModelTestBase.kt
app/src/test/java/app/pachli/components/timeline/NetworkTimelinePagingSourceTest.kt
app/src/test/java/app/pachli/components/timeline/NetworkTimelineViewModelTestBase.kt
app/src/test/java/app/pachli/components/viewthread/ViewThreadViewModelTest.kt
app/src/test/java/app/pachli/db/TimelineDaoTest.kt
app/src/test/java/app/pachli/usecase/TimelineCasesTest.kt
app/src/test/java/app/pachli/util/HttpHeaderLinkTest.kt
app/src/test/java/app/pachli/util/LinkHelperTest.kt
app/src/test/java/app/pachli/util/LocaleUtilsTest.kt
app/src/test/java/app/pachli/util/RickRollTest.kt
app/src/test/java/app/pachli/util/SmartLengthInputFilterTest.kt
app/src/test/java/app/pachli/util/TimestampUtilsTest.kt
app/src/test/resources/robolectric.properties

Associated changes:
- Handle new null/non-null type signatures in overriden methods
- Configure Robolectric to use SDK 33 (current highest supported version)

change: Increase compileSdk and targetSdk to 34

---

app/src/main/res/values/colors.xml
app/src/orange/res/values/flavor-colors.xml

fix: Use Pachli blue and orange for notification icons

---

app/build.gradle
gradle/libs.versions.toml

Enable Kotlin code generation, and use the new room plugin to generate schemas in a reproducible/cacheable way.

fix(deps): update androidx.room to v2.6.0

---

app/src/main/res/values-it/strings.xml

Based on work originally carried out by chaoscalm in https://github.com/pachli/pachli-android/pull/206.

fix(l10n): Update Italian translations

---

core/database/src/main/kotlin/app/pachli/core/database/dao/TimelineDao.kt

`@MapInfo` is deprecated, migrate to `@MapColumn`.

refactor: Use @MapColumn instead of @MapInfo

---

gradle/wrapper/gradle-wrapper.properties
gradlew.bat
settings.gradle.kts
tools/mklanguages/build.gradle.kts
tools/mkserverversions/build.gradle.kts
tools/mvstring/build.gradle.kts

Use new simple property assignment syntax in build files where appropriate.

chore(deps): update dependency gradle to v8.6

---

app/src/main/java/app/pachli/fragment/ViewVideoFragment.kt

fix: Keep the screen on while media is playing

---

.github/workflows/ci.yml
app/src/github/kotlin/app/pachli/di/UpdateCheckModule.kt

Add run CI on the PR not the base.

fix: Add missing import for MoshiConverterFactory

---

app/src/main/java/app/pachli/components/viewthread/edits/ViewEditsViewModel.kt

Content that doesn't start with a block element generates a parse error. This isn't normally seen from Mastodon servers but is seen from content from other servers (e.g,. Akkoma), which can generate:
```
<a href="..."> some text
```
instead of:
```
<p><a href="..."> some text</p>
```
Work around this by ensuring that content-to-be-diffed is wrapped in a `div`.

fix: Show diffs for content that doesn't start with a block element

---

app/src/main/java/app/pachli/components/notifications/NotificationsActivity.kt
app/src/main/res/menu/activity_notifications.xml

Previous code (probably copy/paste error) used R.menu.activity_trending.

fix: Create a dedicated menu for NotificationsActivity

---

app/src/main/AndroidManifest.xml
app/src/main/java/app/pachli/MainActivity.kt
app/src/main/java/app/pachli/TimelineActivity.kt
app/src/main/java/app/pachli/components/account/AccountActivity.kt
app/src/main/java/app/pachli/components/accountlist/AccountListFragment.kt
app/src/main/java/app/pachli/components/announcements/AnnouncementsActivity.kt
app/src/main/java/app/pachli/components/conversation/ConversationsFragment.kt
app/src/main/java/app/pachli/components/followedtags/FollowedTagsActivity.kt
app/src/main/java/app/pachli/components/report/fragments/ReportStatusesFragment.kt
app/src/main/java/app/pachli/components/search/fragments/SearchFragment.kt
app/src/main/java/app/pachli/components/trending/TrendingTagsFragment.kt
app/src/main/java/app/pachli/components/viewthread/edits/ViewEditsFragment.kt
app/src/main/java/app/pachli/fragment/SFragment.kt
app/src/main/res/layout/activity_timeline.xml
core/navigation/README.md
core/navigation/src/main/kotlin/app/pachli/core/navigation/Navigation.kt
feature/lists/src/main/kotlin/app/pachli/feature/lists/ListsActivity.kt

More accurately reflects what it does, and simplies the diffs for upcoming work.

refactor: Rename `StatusListActivity` to `TimelineActivity`

---

app/src/main/java/app/pachli/MainActivity.kt
core/navigation/src/main/kotlin/app/pachli/core/navigation/Navigation.kt

feat: Add left-nav entries for Local, Federated, and Direct Messages

---

core/network/src/main/kotlin/app/pachli/core/network/Server.kt

feat: Disable filters for accounts on servers running Sharkey

---

app/src/main/java/app/pachli/adapter/StatusBaseViewHolder.kt
app/src/main/java/app/pachli/components/conversation/ConversationViewHolder.kt
app/src/main/java/app/pachli/components/viewthread/ViewThreadViewModel.kt

change: Combine variable declaration and assignments

---

app/src/main/res/layout/activity_edit_filter.xml

This makes it a little easier to see what's been changed.

feat: Animate filter keywords when added or removed

---

app/src/main/res/values/strings.xml

Improves the information density when selecting search operators.

refactor: Shorten search operator chip label strings

---

.github/workflows/upload-orange-release-google-play.yml

CI is currently warning about this.

ci: Don't automatically send changes for review

---

app/src/main/java/app/pachli/components/preference/LabPreferencesFragment.kt
app/src/main/java/app/pachli/components/preference/PreferencesFragment.kt

Allows user feedback on this before promoting to a main feature.

refactor: Move tab-tap preference to labs

---

app/src/main/java/app/pachli/MainActivity.kt

Rename some variables and functions in MainActivity to more accurately or consistently reflect what they do.

refactor: Rename variables and functions in MainActivity

---

app/src/main/java/app/pachli/MainActivity.kt
app/src/main/java/app/pachli/components/notifications/NotificationHelper.kt
app/src/main/java/app/pachli/components/notifications/PushNotificationHelper.kt
app/src/main/java/app/pachli/components/notifications/domain/AndroidNotificationsAreEnabledUseCase.kt
app/src/main/java/app/pachli/components/notifications/domain/EnableAllNotificationsUseCase.kt
app/src/main/java/app/pachli/components/preference/NotificationPreferencesFragment.kt

Move enableNotifications and androidNotificationsAreEnabled to usecases.

refactor: Start splitting Notification helpers in to use cases

---

app/src/main/java/app/pachli/MainActivity.kt
app/src/main/java/app/pachli/TabPreferenceActivity.kt
core/navigation/src/main/kotlin/app/pachli/core/navigation/Navigation.kt

Since the activity it launches is called `ListsActivity`.

refactor: Rename ListActivityIntent to ListsActivityIntent

---

app/src/main/java/app/pachli/MainActivity.kt
app/src/main/java/app/pachli/components/account/AccountActivity.kt
app/src/main/java/app/pachli/components/accountlist/AccountListFragment.kt
app/src/main/java/app/pachli/components/announcements/AnnouncementsActivity.kt
app/src/main/java/app/pachli/components/compose/ComposeActivity.kt
app/src/main/java/app/pachli/components/search/SearchActivity.kt
app/src/main/java/app/pachli/components/search/fragments/SearchAccountsFragment.kt
app/src/main/java/app/pachli/components/viewthread/edits/ViewEditsFragment.kt
core/activity/src/main/kotlin/app/pachli/core/activity/AccountSelectionAdapter.kt
core/activity/src/main/kotlin/app/pachli/core/activity/BaseActivity.kt
core/data/src/main/kotlin/app/pachli/core/data/repository/StatusDisplayOptionsRepository.kt
core/preferences/src/main/kotlin/app/pachli/core/preferences/SharedPreferencesRepository.kt
feature/lists/src/main/kotlin/app/pachli/feature/lists/AccountsInListFragment.kt

Continues the work of providing properties with accessors for specific shared preferences.

refactor: Provide properties for more shared preferences

---

app/src/google/kotlin/app/pachli/languageidentification/MlKitLanguageIdentifier.kt

Seen the following crash in user reports:
```
com.google.android.gms.common.api.ApiException: 17:
API: ModuleInstall.API is not available on this device.
Connection failed with:
ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}
```
Doesn't appear to be properly documented anywhere I can find. To work around this catch exceptions when checking for MLKit modules or installing them and return defaults.

fix: Prevent crash when ModuleInstall.API is unavailable

---

core/network-test/src/main/kotlin/app/pachli/core/network/di/test/FakeMastodonApiModule.kt

Tests that rely on stubbing the MastodonAPI may have incorrect behaviour if some of the API methods called by the system-under-test are not stubbed. This can be difficult to track down.
Make this easier by adding a default answer for the MastodonAPI used in tests. Any un-stubbed methods will throw an `AssertionError` with enough information to identify the method that should be stubbed and where it was called from.

test: Ensure that all relevant MastodonAPI methods are stubbed

---

app/src/main/java/app/pachli/components/compose/view/ComposeScheduleView.kt

The MaterialTimePicker library has a bug that results in the "Cancel" and "Ok" buttons on the dialog being cut off.
See https://github.com/material-components/material-components-android/issues/3584
Work around this by updating their layout params and explicitly setting the "bottomToBottom" constraint to their parent.

fix: Don't clip buttons when choosing scheduled post time

---

gradle/libs.versions.toml

Includes associated update to lint version.

chore(deps): update agp to v8.7.1

---

gradle/libs.versions.toml

Update lint version appropriately.

chore(deps): update agp to v8.7.2

---

app/src/main/res/values/donottranslate.xml

feat: Add Norsk Nynorsk as a selectable language

---

app/build.gradle.kts
app/lint-baseline.xml
app/proguard-rules.pro
app/src/main/java/app/pachli/util/CryptoUtil.kt
gradle/libs.versions.toml
licenses/libraries/subway_tooter.json

"BKS" in the error refers to "Bouncycastle KeyStore". Remove all usage of the Bouncycastle library from the code, re-implementing one required function based on code from SubwayTooter. Add a license entry that acknowledges this.
Fixes #1143

fix: "KeyStoreException: BKS not found" error during login

---

app/src/main/java/app/pachli/components/timeline/viewmodel/CachedTimelineRemoteMediator.kt
app/src/main/java/app/pachli/network/ContentFilterModel.kt
app/src/test/java/app/pachli/components/timeline/StatusMocker.kt
core/data/src/main/kotlin/app/pachli/core/data/repository/notifications/NotificationsRemoteMediator.kt
core/database/schemas/app.pachli.core.database.AppDatabase/15.json
core/database/src/main/kotlin/app/pachli/core/database/AppDatabase.kt
core/database/src/main/kotlin/app/pachli/core/database/dao/NotificationDao.kt
core/database/src/main/kotlin/app/pachli/core/database/dao/TimelineDao.kt
core/database/src/main/kotlin/app/pachli/core/database/model/StatusEntity.kt
core/database/src/main/kotlin/app/pachli/core/database/model/TranslatedStatusEntity.kt
core/database/src/test/kotlin/app/pachli/core/database/dao/TimelineDaoTest.kt

TimelineStatusEntity is going to be repurposed for the table that maps between a timeline (not just the home timeline) and the statuses on that timeline.

refactor: Rename TimelineStatusEntity to StatusEntity

---

app/src/main/java/app/pachli/appstore/CacheUpdater.kt
app/src/main/java/app/pachli/components/conversation/ConversationsViewModel.kt
core/data/src/main/kotlin/app/pachli/core/data/repository/notifications/NotificationsRepository.kt
core/database/src/main/kotlin/app/pachli/core/database/dao/ConversationsDao.kt
core/database/src/main/kotlin/app/pachli/core/database/dao/StatusDao.kt

The `setVoted` method set the entire `Poll` value, so rename it be more accurate.

change: Rename setVoted to setPoll

---

app/src/main/java/app/pachli/components/timeline/CachedTimelineRepository.kt
core/data/src/main/kotlin/app/pachli/core/data/repository/notifications/NotificationsRepository.kt
core/database/src/main/kotlin/app/pachli/core/database/dao/StatusDao.kt
core/database/src/main/kotlin/app/pachli/core/database/dao/TimelineDao.kt
core/database/src/test/kotlin/app/pachli/core/database/dao/AccountEntityForeignKeyTest.kt

It's a better fit for them than TimelineDao.

change: Move DAO methods on StatusViewData in to StatusDao

---

app/lint-baseline.xml
app/src/fdroid/kotlin/app/pachli/updatecheck/UpdateCheck.kt
app/src/github/kotlin/app/pachli/updatecheck/UpdateCheck.kt
app/src/google/kotlin/app/pachli/updatecheck/UpdateCheck.kt
app/src/main/java/app/pachli/MainActivity.kt
app/src/main/java/app/pachli/adapter/StatusBaseViewHolder.kt
app/src/main/java/app/pachli/adapter/StatusDetailedViewHolder.kt
app/src/main/java/app/pachli/components/account/AccountActivity.kt
app/src/main/java/app/pachli/components/notifications/PushNotificationHelper.kt
app/src/main/java/app/pachli/components/notifications/domain/EnableAllNotificationsUseCase.kt
app/src/main/java/app/pachli/components/preference/PreferencesFragment.kt
app/src/main/java/app/pachli/components/search/fragments/SearchStatusesFragment.kt
app/src/main/java/app/pachli/components/viewthread/edits/ViewEditsAdapter.kt
app/src/main/java/app/pachli/fragment/SFragment.kt
app/src/main/java/app/pachli/service/PachliTileService.kt
app/src/main/java/app/pachli/util/StatusViewHelper.kt
app/src/main/java/app/pachli/util/UpdateShortCutsUseCase.kt
app/src/main/java/app/pachli/view/SliderPreference.kt
core/activity/src/main/kotlin/app/pachli/core/activity/CustomEmojiHelper.kt
core/activity/src/main/kotlin/app/pachli/core/activity/ImageLoadingHelper.kt
core/domain/src/main/kotlin/app/pachli/core/domain/DownloadUrlUseCase.kt
core/ui/src/main/kotlin/app/pachli/core/ui/ClickableSpanTextView.kt
feature/login/lint-baseline.xml
feature/login/src/main/kotlin/app/pachli/feature/login/LoginActivity.kt
feature/login/src/main/kotlin/app/pachli/feature/login/RickRoll.kt
gradle/libs.versions.toml

This also updates lint to the matching version 31.9.0 which introduces a number of new checks, mostly around using KTX extensions. The suggested fixes are applied.

chore(deps): Update agp to 8.9.0

---

app/src/main/java/app/pachli/components/viewthread/ViewThreadFragment.kt
app/src/main/java/app/pachli/components/viewthread/ViewThreadViewModel.kt
app/src/test/java/app/pachli/components/viewthread/ViewThreadViewModelTest.kt

- Use a `Result` with a `PachliError` subclass instead of a single sealed interface for both.
- Use consistent `uiResult` terminology.
- Extract UI binding code to separate functions.

refactor: Modernise the ViewThread* code

---

app/src/main/java/app/pachli/components/followedtags/FollowedTagsAdapter.kt
app/src/main/java/app/pachli/components/search/adapter/SearchHashtagsAdapter.kt
app/src/main/res/layout/item_hashtag.xml
app/src/main/res/values/strings.xml

- Collect and show the stats.
- Handle the case where less/more than 7 days of data is available

feat: Show hashtag usage and account stats in search results

---

app/src/main/java/app/pachli/adapter/ReportNotificationViewHolder.kt
app/src/main/java/app/pachli/viewdata/NotificationViewData.kt

Closes #1446. It is ultimately a quick fix, it has been a while since I actively dealt with Android apps, so my code still needs to be properly reviewed

fix: Prevent crash, correctly pass report data to notifications

---

gradle/libs.versions.toml

fix(deps): update agp to v8.9.1

---

app/src/main/java/app/pachli/MainActivity.kt

The drawer library's `DrawerImageLoader` can leak the object it's initialised with. This is problem if it's initialised with the activity's `RequestManager` (Glide) as it previously was, as that holds a reference to the activity, so the activity is leaked for a period of time.
Fix this by not passing in `RequestManager`, and using `Glide.with(View)` in this instance.

fix: Don't leak MainActivity in DrawerImageLoader

---

app/src/main/java/app/pachli/components/compose/ComposeActivity.kt

Previous code used colour for disabled items, and also had incorrect logic for choosing the colours.
Material uses a specific resource to set the alpha value for the disabled state of a view or drawable. Use that instead of adjusting colours.

fix: Use alpha instead of colour for disabled items when composing

---

app/src/main/java/app/pachli/components/accountlist/adapter/AccountAdapter.kt
app/src/main/java/app/pachli/util/ListUtils.kt

Code by cbeyls, https://github.com/tuskyapp/Tusky/pull/4443

refactor: Optimize ListUtils.removeDuplicates()

---

core/ui/src/main/kotlin/app/pachli/core/ui/ClickableSpanTextView.kt

There's a bug on Android before O_MR1. Long pressing to select text, then long pressing again on the textview can crash with this:
```
java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:434)
at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:155)
at android.text.SpannableString.setSpan(SpannableString.java:46)
at android.text.Selection.setSelection(Selection.java:76)
at android.widget.Editor$SelectionModifierCursorController.resetDragAcceleratorState(Editor.java:5462)
at android.widget.Editor$SelectionModifierCursorController.onTouchEvent(Editor.java:5316)
at android.widget.Editor.onTouchEvent(Editor.java:1364)
at …
```

fix: Prevent IndexOutOfBoundsException on text long press

---

core/ui/src/main/kotlin/app/pachli/core/ui/CustomEmojiHelper.kt

Previous code scaled emoji to fit within a bounding square that roughly matched the view's line height. This meant that emoji wider than tall (i.e., landscape dimensions) were significantly squashed and could become unreadable.
Fix this by scaling the emoji down so the height fits within the view's line height, but allow the emoji to run wider than that.

fix: Correctly display emoji with landscape dimensions

---

app/src/main/java/app/pachli/components/timeline/viewmodel/NetworkTimelineViewModel.kt

Previous change inadvertently removed this filter. Posts filtered with a "warn" were still warned, but posts filtered with a "hide" were shown.

fix: Correctly hide filtered posts from network timelines

---

app/src/main/java/app/pachli/components/conversation/ConversationsViewModel.kt
app/src/main/java/app/pachli/components/timeline/viewmodel/CachedTimelineViewModel.kt
app/src/main/java/app/pachli/components/timeline/viewmodel/NetworkTimelineViewModel.kt
app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt

Previous code constructed `StatusViewData` objects for each status in the timeline, then applied any `Hide` filters.
Now, determine the filter action for each status first, filter out any that should be hidden, then create the `StatusViewData`.

refactor: Filter statuses early
